CMakeLists.txt
README.md
cmake/CMakeSettings.cmake
test/CMakeLists.txt
test/cufisher_price.cu
test/example_add.cu
test/fisher_price.cpp

As a trivial starting point, this copies across the minimal build setup from Excalibur/emcuda but with the CMake min version bumped to 3.17. This [recent version](https://cmake.org/cmake/help/latest/release/3.17.html) is chosen as it provides very simple configure/use of the CUDA toolkit through the [FindCUDAToolkit](https://cmake.org/cmake/help/v3.17/module/FindCUDAToolkit.html#module:FindCUDAToolkit) module. 
The C++/CUDA standard is fixed at C++14 for now, but can be reviewed, along with any min requirements on CUDA version or compute capability.  
To check that this works a, for now arbitrary, `test` directory holds a couple of programs to exercise CPU/CUDA builds. Those can be tried locally, I haven't thought about what, if any, CI we'll use.

Add minimal buildscript and test programs

---

CMakeLists.txt
README.md

CMake 3.18 introduces the new variable `CMAKE_CUDA_ARCHITECTURES` and target property `CUDA_ARCHITECTURE`:
- https://cmake.org/cmake/help/v3.18/variable/CMAKE_CUDA_ARCHITECTURES.html
- https://cmake.org/cmake/help/v3.18/prop_tgt/CUDA_ARCHITECTURES.html
These list the required architectures to generate device code for, and set the required CUDA compiler flags. See e.g. https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-generations
To better support selection of CUDA architecture flags, require CMake 3.18 as the minimum. `CMAKE_CUDA_ARCHITECTURES` is _not_ set so the defaults for the compiler will be used until the range of supported devices is defined. 
However, it can still be set manually via, e.g. `cmake -DCMAKE_CUDA_ARCHITECTURES="62;71" <args>", and I'd guess it can …

Bump minimum required CMake to 3.18

---

.flake8
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSES/CC-BY-ND-4.0.txt

Code of conduct is from CERN, which seems to be perfect for out project - thanks to @paulgessinger for having textified it in Acts.
Contribution guide is also an adapted version from Acts (thanks!), so makes reference to things that we have not yet setup in AdePT (marked by **FIXME**), but does form a good basis for discussion.
Note that as well as C++ I added some draft guidance for Python and Markdown files in the project.
Closes #3

Add draft contribution and CoC guides

---

.clang-format
.github/workflows/clang-format.yml

Initial clang-format import using VecGeom's style. Add workflow to check/apply changes on pushes and pull requests.
Closes #10

Add clang-format file and workflow

---

CMakeLists.txt
base/inc/AdePT/Atomic.h
base/inc/AdePT/BlockData.h
base/inc/AdePT/Utils.h
base/inc/AdePT/mpmc_bounded_queue.h
test/CMakeLists.txt
test/test_atomic.cu
test/test_queue.cu
test/test_track_block.cu

The templated type adept::Atomic_t dispatches std::atomic interfaces to the appropriate backend (CPU or CUDA). Atomic_t objects adopt pre-allocated memory, using the static function MakeInstanceAt, on a buffer of length sizeof(Atomic_t<Type>). Unit test: test_atomic.
This adds also a new concurrent container adept::BlockData. The block is templated on the data type, allocating the demanded number of elements in a pre-allocated buffer. The number of bytes to be allocated is returned by the static method BlockData<Type>::SizeOfInstance. The method SizeOfAlignAware should be used for allocating multiple blocks in the same buffer. The method NextElement gives write access to the next unused element, and the bracket operator can be used for read access. Unit test: test_track_block
A new …

Added atomic ops type and BlockData concurrent container

---

test/CMakeLists.txt
test/cufisher_price.cu

This pull request adds the CUDA version of the fisher_price example. The CUDA kernel consists of the 'process' (energy loss and pair production) run for each particle/step. For each iteration the 'main' schedules as many CUDA threads as particles in flight. New particle which are created during the pair-production process are pushed into the common BlockData container. Particles which die (E=0) are released from the container and the slots are used by new ones.

adding cuda version of fisher_price example

---

CMakeLists.txt
README.md
test/FisherPrice_Alpaka/CMakeLists.txt
test/FisherPrice_Alpaka/alpaka_fisher_price.cu
test/FisherPrice_Alpaka/part.h
test/FisherPrice_Alpaka/particleProcessor.h
test/FisherPrice_Alpaka/particleStack.h
test/FisherPrice_Alpaka/sensitive.h
test/FisherPrice_Alpaka/vec3.h

Hello,
This PR includes the current version of the FisherPrice code reworked to interface with Alpaka.
At the moment I put authors of all the c++ headers as Dvaide/myself. I think some/all of the classes might have contributions from @drbenmorgan - should I therefore add you as an author to some/all of them too? (also I don't know if the versions I started from have any other authors I'm not aware of to add).
This is a WIP for now, but starting it so as to coordinate with code from @drbenmorgan. In particular I added doxygen (as requested in the contribution requirements) to the c++ classes I picked up from FisherPrice. These classes are the same as the ones in the CUDA/c++ branch, so presumably we don't want people independently spending time to add doxygen. This also brings a general …

Adding the Alpaka version of FisherPrice

---

base/inc/AdePT/Atomic.h
base/inc/AdePT/BlockData.h
base/inc/AdePT/mpmc_bounded_queue.h
base/inc/CopCore/include/CopCore/CopCore.h
base/inc/CopCore/include/CopCore/VariableSizeObj.h
test/CMakeLists.txt
test/test_track_block.cu

The PR addresses #18 fixing all types of allocation and copying of BlockData types. The unit test test_track_block was extended to cover more features of BlockData. Closing #18 
A documented version of the VariableSizeObj.h header is now available in CopCore (separate commit), removing the current dependencies of some base types (queues and data blocks) on VecGeom. Closing #14

Fix BlockData allocation and copying on host.

---

test/FisherPrice_Alpaka/CMakeLists.txt

This addresses the question in one of our catchups about whether Alpaka is required or not. It isn't, but CMake will moan if it's not found. This just quietens that warning, but the behaviour is otherwise unchanged

Quieten CMake warnings when not finding Alpaka

---

base/inc/CopCore/include/CopCore/Allocator.h
base/inc/CopCore/include/CopCore/CopCore.h
base/inc/CopCore/include/CopCore/VariableSizeObjAllocator.h
test/CMakeLists.txt
test/run_simulation.hpp
test/sim_kernels.h

* A general allocator utility specialised on the backend being used. Usage:
```
copcore::Allocator<Type, backend> myAlloc; // backends defined in Global.h, constructor takes optional device id
Type *obj_ptr = myAlloc.allocate(10, params...); // allocates an array of 10 Type objects, passing params... to their constructor
...
myAlloc.deallocate(obj_ptr, 10); // deallocates the array, calling optionally ~Type (if number of elements passed) 
```
* test_launcher extended to demonstrate usage of the new allocator for (basic) types. Added an example for launching lambda functions.

Allocators

---

base/inc/CopCore/include/CopCore/Global.h
base/inc/CopCore/include/CopCore/Launcher.h
test/run_simulation.hpp

This fixes multiple definitions when including Global.h due to the implementation of BackendName containing full specialisations for backends. Now BackendName implemented as templated function.

Fix backend name

---

test/CMakeLists.txt

Move the option --extended-lambda out of the generator expression
guarded by Debug and RelWithDebInfo.

Fix Release build of tests

---

examples/CMakeLists.txt
examples/Example1/CMakeLists.txt
examples/Example1/example1.cu
physics/processes/inc/energy_loss.h
physics/processes/inc/pair_production.h
physics/processes/inc/process.h
physics/processes/inc/process_list.h
tracking/inc/track.h

This is a new example where some basic infrastructure is implemented for handling a set of processes inheriting from the same base class. A class process_list manages all available processes. The files (even if only example ones, to be replaced in the future) have been put in the appropriate directories to exercise the directory structure. MParrays are used for queues for each of the process. The main program implements some basic workflow checking first for the interactions length (dummy), selecting the appropriate queues for the particles and then calling the pipeline of processes. 
This example is an attempt of some basic 'architecture' of stepping sequence with a split between CPU and GPU calls.

adding example1 demonstrating workflow with pipelining kernels for processes

---

LICENSES/LGPL-2.1-or-later.txt
base/inc/CopCore/LICENSES/LGPL-2.1-or-later.txt
base/inc/CopCore/include/CopCore/Ranluxpp.h
base/inc/CopCore/include/CopCore/mulmod.h
test/CMakeLists.txt
test/test_ranluxpp.cu

Copied from ROOT, with support for only one luxury level (`p=2048`). The main interface for now is `RanluxppDouble`, but we can implement more classes that use less random bits to produce a `float`.
The added test shows how the state can be transferred between host and device via a `cudaMemcpy` and checks that the generated numbers on host and device are identical.

RANLUX++ for host and device

---

examples/Raytracer_Benchmark/CMakeLists.txt
examples/Raytracer_Benchmark/LoopNavigator.h
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp
examples/Raytracer_Benchmark/RaytraceBenchmark.cu
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h
examples/Raytracer_Benchmark/kernels.h

I added two new files: ```LoopNavigator.h``` and ```kernels.h```.
I refactored the navigation methods as a separate class ```LoopNavigator```. These methods were defined before in ```Raytracer.cpp```.
The rays are used now from ```BlockData<T>``` containers. ```kernels.h``` contains the function ```generateRays``` which is responsible to allocate slots for the ```BlockData```.

LoopNavigator Class and use rays from BlockData<T> containers

---

examples/Raytracer_Benchmark/ArgParser.h
examples/Raytracer_Benchmark/LoopNavigator.h
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp
examples/Raytracer_Benchmark/RaytraceBenchmark.cu
examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h
examples/Raytracer_Benchmark/kernels.h

I refactored the calling sequence for CPU and GPU in order to use ```copcore::Launcher``` framework.
In ```kernels.h```, I added the ```renderKernels``` function which propagates the rays and write the image for both backends.
In ```RaytraceBenchmark.hpp```, I added ```runSimulation``` function which is dependent on the backend and replaces ```RaytraceBenchmarkGPU``` or ```RaytraceBenchmarkCPU``` functions.

Refactor the calling sequence for CPU/GPU to use copcore::Launcher

---

examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h

The backend-dependent launcher part was accessing wrongly cuda::GeoManager. Removed un-needed fMaxDepth, and some dead code.

Fix for the ray-tracer example in debug mode.

---

base/inc/AdePT/Atomic.h
base/inc/AdePT/BlockData.h
base/inc/AdePT/LoopNavigator.h
base/inc/AdePT/MParray.h
base/inc/AdePT/Utils.h
base/inc/AdePT/mpmc_bounded_queue.h
base/inc/CopCore/include/CopCore/Allocator.h
base/inc/CopCore/include/CopCore/CopCore.h
base/inc/CopCore/include/CopCore/Global.h
base/inc/CopCore/include/CopCore/Launcher.h
base/inc/CopCore/include/CopCore/Macros.h
base/inc/CopCore/include/CopCore/Ranluxpp.h
base/inc/CopCore/include/CopCore/VariableSizeObj.h
base/inc/CopCore/include/CopCore/VariableSizeObjAllocator.h
base/inc/CopCore/include/CopCore/launch_grid.h
base/inc/CopCore/include/CopCore/mulmod.h
examples/Example1/example1.cu
examples/Example2/example2.cu
examples/FisherPrice_cu/cufisher_price.cu
examples/FisherPrice_cu/cufisher_price_v2.cu
examples/Raytracer_Benchmark/Color.h
examples/Raytracer_Benchmark/Raytracer.h
examples/Raytracer_Benchmark/kernels.h
test/run_simulation.hpp
test/sim_kernels.h
test/test_atomic.cu

Testing and discussion showed that using the full Allen approach would not work immediately for AdePT due to symbol clashes from the requirement for a mix of CPU/GPU code. However, its macro system is still useful to simplify markup of functions and indicate CUDA use and the device-compile pass.
Implement a simple header in CopCore based on Allen and Guilherme Amadio's prototype system. Define macros to indicate:
- Use of a CUDA compiler (i.e. compiling code as CUDA)
- Compilation is on the device pass
Use Allen's style of defining CUDA's `__host__` etc keywords as
empty defines when compiling for a host/non-cuda compiler.
Migrate CopCore, AdePT, example, and tests code to use the new macros.
There are some warnings in the `examples`, but I need to update my VecGeom install with the …

Use Allen/prototype macros for host/device markup

---

base/inc/CopCore/include/CopCore/Macros.h

The header `VecGeom/backend/cuda/Interface.h` includes some files from
the CUDA toolkit that also define these keywords. Avoid warnings by
first checking if the keywords are already defined.

Avoid redefinition of CUDA keywords

---

CTestConfig.cmake
Jenkinsfile
examples/Example1/CMakeLists.txt
jenkins/adept-ctest.cmake

Added Jenkinsfile with the basic pipeline.
Added the script jenkins/adept-ctest.cmake to drive the update, configuration, build and test and publish results to [Cdash](https://cdash.cern.ch/index.php?project=AdePT)
The initial jenkins jobs (nightly for the time being) are available at https://lcgapp-services.cern.ch/spi-jenkins/view/AdePT/

Adding CTest/Jenkins infrastructure

---

base/inc/CopCore/include/CopCore/Global.h
examples/Example1/example1.cu
examples/Example2/example2.cu
physics/processes/inc/pair_production.h

The `assert()` would only be present for Debug builds, leaving Release builds with an "illegal memory access" due to accessing nullptr. Use the existing `COPCORE_EXCEPTION` and extend it to print a message on the device. This still isn't perfect because all threads will print, but better than developers wondering what happened.

Abort simulation if secondary cannot be produced

---

examples/Example1/example1.cu
examples/Example2/example2.cu

`number_of_secondaries` is the total number of secondaries produced by this track. To accumulate a global value, `example1` must only add the difference produced in the current step.
Also change the code in `example2` to match the other two and always add to the atomic (we need a more performant version of the scoring anyway).

Correct number of secondaries for example1

---

physics/processes/inc/pair_production.h

This makes `example4` reproducible because the particle's charge decides if it is subjected to the magnetic field.

Initialize PDG for secondary tracks

---

base/inc/AdePT/LoopNavigator.h
examples/Example6/example6.cu
magneticfield/inc/fieldPropagatorConstBz.h

When a particle leaves the current volume or enters a daughter, we need to relocate to the next volume. This could involve walking the hierarchy which is expensive, at least in the current `LoopNavigator`. The problem is that if only one particle needs relocation, all others have to wait.
As a first step, move the relocation step out of navigation, which is called from the magnetic field, to a common place when a particle is detected to need it. This already improves the total runtime from around 1.4s to 1.3s on my system.
---
As there are usually fewer particles to be relocated than there are threads on the GPU, we can use one level of parallelism to check daughter volumes in parallel. This improves the total runtime from around 1.3s to 1.2s on my system.
---
*Note*: I think it would be …

example6: Split and parallelize relocation to next volume

---

CMakeLists.txt
examples/Example1/CMakeLists.txt
examples/Example2/CMakeLists.txt
examples/Example4/CMakeLists.txt
examples/Example5/CMakeLists.txt
examples/Example6/CMakeLists.txt
examples/FisherPrice_cu/CMakeLists.txt
examples/Raytracer_Benchmark/CMakeLists.txt
examples/field_cu/CMakeLists.txt
test/CMakeLists.txt

Add a CMake `INTERFACE` target for AdePT with main locations of headers and dependency on CopCore as usage requirements. This allows all of the examples and tests to use `target_link_libraries` to pick up all the headers (and pave the way to simplify the repo layout in a separate PR), and these have been updated accordingly.
The AdePT target is not totally complete in that it doesn't declare its dependence on VecGeom (through `LoopNavigator.h` in the base, and others in magneticfield/tracking/physics) yet. That's deliberate as how to correctly declare the CUDA vs CPU only usage requirements needs some thought, but the target as implemented here is a good first step.

Create and use minimal interface target for AdePT

---

examples/Example1/example1.cu
examples/Example2/example2.cu
examples/Example6/example6.cpp
examples/Example6/example6.cu
tracking/inc/printTracks.h

This restores the output of the examples, except for rounding errors. Most of those are in `example4` and `example6` because the global energy deposit is a `float`, which doesn't have enough precision for the range of energies we need. In addition, `example4` doesn't produce two secondaries at the end, probably also because of rounding changes for the threshold energy.

Fixes to deal with change of units

---

examples/Example9/example9.cu
examples/TestEm3/TestEm3.cu

Before CUDA 11.1.0, `cudaStreamWaitEvent` did not have a default value for the `flags` parameter. Instead the documentation verbally required that the passed argument "must be 0", so pass this value explicitly to allow compilation with older versions.

Fix compilation with older versions of CUDA

---

examples/Example9/electrons.cu
examples/Example9/example9.cu
examples/Example9/example9.cuh
examples/TestEm3/TestEm3.cu
examples/TestEm3/TestEm3.cuh
examples/TestEm3/electrons.cu

Using templates was a good idea, but is highly confusing for profiling because Nsight Compute doesn't show template parameters for kernels. Split into separate kernels that call the instantiated template. The compiler takes care of inlining, resulting in only minor performance penalties that are barely measurable.

Separate TransportElectrons and TransportPositrons

---

CMakeLists.txt
examples/Example2/CMakeLists.txt
examples/Example4/CMakeLists.txt
examples/Example6/CMakeLists.txt
examples/Example8/CMakeLists.txt
examples/Example9/CMakeLists.txt
examples/Raytracer_Benchmark/CMakeLists.txt
examples/TestEm3/CMakeLists.txt
examples/field_cu/CMakeLists.txt
test/CMakeLists.txt

Generate line info for the `RelWithDebInfo` configuration and full device debug information only in `Debug` configuration because that completely disables optimizations.

Unify debugging levels for CUDA

---

examples/Example9/example9.cu
examples/Example9/example9.cuh
examples/TestEm3/TestEm3.cu
examples/TestEm3/TestEm3.cuh

The compiler cannot see that we're going to call the functions through their pointers, so it underestimates the number of required registers. By including calls to the functions we force the compiler to account for the register usage.

Work around underestimated register count

---

base/inc/AdePT/SparseVector.h
examples/Raytracer_Benchmark/CMakeLists.txt
examples/Raytracer_Benchmark/Color.h
examples/Raytracer_Benchmark/Material.h
examples/Raytracer_Benchmark/README.md
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp
examples/Raytracer_Benchmark/RaytraceBenchmark.cu
examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h
examples/Raytracer_Benchmark/box_sphere.gdml
examples/Raytracer_Benchmark/kernels.h

Add reflection and refraction model for transparent objects. Add exponential attenuation for rays which traverse transparent layers. Structure storing optical properties (transparency, refraction index, object color) for every logical volume.

Add reflection and refraction in RaytraceBenchmark

---

base/inc/CopCore/include/CopCore/Ranluxpp.h
examples/Example9/electrons.cu
examples/Example9/example9.cuh
examples/Example9/gammas.cu
examples/TestEm3/TestEm3.cuh
examples/TestEm3/electrons.cu
examples/TestEm3/gammas.cu

This is more correct because static skipping leads to overlapping sequences and more efficient because there is only one `Advance`.

Branch RNG state when generating secondaries

---

examples/Example9/electrons.cu
examples/Example9/gammas.cu
examples/TestEm3/electrons.cu
examples/TestEm3/gammas.cu

When the primary is killed, we can reuse the state for a secondary instead of branching twice.
---
Creating a branched RNG state is faster before threads start diverging for the discrete interactions.
---
(please don't squash, the performance development might be of interest in the future)

Optimize RNG some more

---

base/inc/CopCore/include/CopCore/Global.h

Some function bodies are defined based on `COPCORE_CUDA_COMPILER`. When linking compiled objects from both `.cu` and `.cpp` files (such as the RaytraceBenchmark), and if the functions were not actually inlined (for example in a Debug) build, the linker got to pick one and the wrong implementation might be used.
This fixes #122 on my machine.

Fix (some) ODR violations in CopCore

---

examples/CMakeLists.txt
examples/Example10/CMakeLists.txt
examples/Example10/README.md
examples/Example10/electrons.cu
examples/Example10/example10.cpp
examples/Example10/example10.cu
examples/Example10/example10.cuh
examples/Example10/example10.h
examples/Example10/gammas.cu
examples/Example10/relocation.cu

There are two levels:
1. On the device, each transportation kernel can make several steps (up to a configurable limit, currently 4) as long as the particle stays alive and inside the volume. At volume boundary, relocation still happens in a separate kernel.
2. The host submits multiple kernels (currently 4 per particle type) into the appropriate streams and only synchronizes once at the end. Proper ordering on the device is ensured via events, extending the previous approach. The code uses an upper bound on the number of particles to determine the launch configuration.
In total, this reduces the number of iterations for `trackML` from 214 with `example9` to 29 using the code from the new example with identical results (energy deposition, number of secondaries, number of hit volume …

Example10, reduce number of iterations

---

examples/CMakeLists.txt
examples/Example11/CMakeLists.txt
examples/Example11/README.md
examples/Example11/electrons.cu
examples/Example11/example11.cpp
examples/Example11/example11.cu
examples/Example11/example11.cuh
examples/Example11/example11.h
examples/Example11/gammas.cu
magneticfield/inc/fieldPropagatorConstBz.h

In this new example, the relocation queue is removed, and a call to `BVHNavigator::LocateToNextVolume()` is made within the transportation kernels instead. Please validate on your side as well. I seem to at least get the same results as Example9, just slightly faster (0.73s vs 0.90s before):
```sh
epsftws build $ BuildProducts/bin/example9 -gdml_name trackML.gdml > example9.log
epsftws build $ BuildProducts/bin/example11 -gdml_name trackML.gdml > example11.log
epsftws build $ diff example9.log example11.log 
236c236
< Run time: 0.9069
---
> Run time: 0.7363
```
*Update*: After swapping the `LoopNavigator` with `BVHNavigator` in the field propagator, the results are still the same, but the speedup is a lot larger:
```
epsftws build $ BuildProducts/bin/example9  -gdml_name trackML.gdml > …
```

Example11, same as Example9, but using BVH class from VecGeom on GPU

---

base/inc/CopCore/include/CopCore/Ranluxpp.h

It appears I never validated the final version of commit 02f73620f6 ("Branch RNG state when generating secondaries") after dropping the call to `Advance()` for the branched RNG state with the other commits to optimize RNG usage from PR #117 (commits 127b7be676 ("Reuse RNG state of killed particles") and 08e4301a98 ("Move RNG branching to reduce thread divergence")). Testing current master reveals errors in comparison to Geant4 in the order of multiple per mill. Restore the call to `Advance()` for better decorrelation of the branched RNG.

Decorrelate branched RNG state

---

examples/Raytracer_Benchmark/README.md
examples/Raytracer_Benchmark/RaytraceBenchmark.cu
examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h
examples/Raytracer_Benchmark/kernels.h

The rays are transported only to the next boundary at every step. Two containers of indices are used. The rays used at every step are taken based on the indices from the first container. The second one stores temporary the indices of the alive rays. Before moving to the next step, the first and second containers are swapped and the second container is cleared.
Every ray has a new parameter, called ```reflection```. The new generated reflected rays have this parameter set (only for the current step). ```reflection``` is used for getting the indices of reflected rays.

transport rays to the next boundary at every step in RaytraceBenchmark

---

examples/Example11/example11.cu
examples/Example9/example9.cu
examples/TestEm3/TestEm3.cu

This improves performance by up to a factor of 2x if a significant fraction of the runtime is spent on waiting for these particles, until eventually running into the previous limit of 1000 iterations.
---
For testing with `cms2018.gdml`, be sure to have a VecGeom with https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/831 to avoid stuck particles due to `DistanceToOut` and `Contains` disagreeing for some polyhedra...

Detect charged particles that are looping

---

base/inc/AdePT/BVHNavigator.h
base/inc/AdePT/LoopNavigator.h
examples/Example10/gammas.cu
examples/Example10/relocation.cu
examples/Example11/gammas.cu
examples/Example6/example6.cu
examples/Example7/TestEm3.cuh
examples/Example7/electrons.cu
examples/Example7/gammas.cu
examples/Example7/relocation.cu
examples/Example8/example8.cu
examples/Example9/gammas.cu
examples/Example9/relocation.cu
examples/TestEm3/TestEm3.cuh
examples/TestEm3/electrons.cu
examples/TestEm3/gammas.cu
magneticfield/inc/fieldPropagatorConstBz.h

The previous code pushed on every step which introduces systematic errors. Instead only push when reaching a boundary, also removing the problematic case that a slightly pushed point is relocated and the track itself is stuck at one position.
Also correct the handling of negative values from `DistanceToIn` in `LoopNavigator`.
---
I tested all examples with the `cms2018` geometry and I think the pushing when at boundary resolves all stuck particles. For validation, I ran with 1 million electrons on TestEm3 and didn't see much of a difference, presumably because the geometry is very simple.

Only push when relocating a track

---

examples/TestEm3/TestEm3.cu

* Correct initial number of electrons
* Avoid legacy default stream during simulation
These changes only have a very minor effect in the current setup, but are critical when using multiple threads.

Fixes for TestEm3

---

base/inc/AdePT/NVTX.h
examples/Example9/example9.cu

Include a tracer to annotate profiling, e.g.:
```diff
+  NVTXTracer tracer("SimulationLoop");
```
The class is a bit rudimentary and can/should be extended, but it at least supports cycling through a few colours and setting tags for the different phases of the workflow.
When compiling with `-DUSE_NVTX`, example 9 looks as follows in nsight systems:

Add a simple NVTX helper class for profiling

---

examples/Example11/electrons.cu
examples/Example11/example11.cu
examples/Example11/example11.cuh
examples/Example11/gammas.cu
examples/Example9/electrons.cu
examples/Example9/example9.cu
examples/Example9/example9.cuh
examples/Example9/gammas.cu
examples/Example9/relocation.cu
examples/TestEm3/TestEm3.cu
examples/TestEm3/TestEm3.cuh
examples/TestEm3/electrons.cu
examples/TestEm3/gammas.cu
examples/TestEm3MT/TestEm3.cu
examples/TestEm3MT/TestEm3.cuh
examples/TestEm3MT/electrons.cu
examples/TestEm3MT/gammas.cu

This saves 8 bytes per track and a bunch of global memory accesses. Ideally, we would only save the `NavIndex_t` but there is no API to directly retrieve the member `fNavInd` (`GetNavIndex` expects a level and both getting and using that requires walking the hierarchy).

Store only one NavStateIndex

---

base/inc/AdePT/SparseVector.h
base/inc/CopCore/include/CopCore/Global.h
examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
test/test_sparsevector.cu
test/test_sparsevector_cpu.cpp

This removes the use of the is_on_device macro that confused the compiler producing undetermined behavior.

Remove broken is_on_device macro and its use in SparseVector.

---

CMakeLists.txt
examples/CMakeLists.txt
examples/Example12/CMakeLists.txt
examples/Example12/README.md
examples/Example12/electrons.cu
examples/Example12/example12.cpp
examples/Example12/example12.cu
examples/Example12/example12.cuh
examples/Example12/example12.h
examples/Example12/gammas.cu

The example implements TestEm3-like workflow, but the geometry can be taken from an arbitrary GDML file. 
* The geometry is first read by the Geant4 parser and the G4HepEm state is initialized based on this
* The geometry is then imported via vecgeom::vgdml and the geometry hierarchy is visited in parallel with the Geant4 one to match G4LogicalVolume<->vecgeom::LogicalVolume and build the LUT (logical volume index) -> (G4HepEm material-cut couple index)
* GPU data is initialized and showering/scoring is done as in TestEm3
* Scoring is done per placed volume, no sensitivity selection
I tested this with cms2018.gdml, it works and gives reasonable (at first glance) results (the energy deposit per primary equal to the primary energy) when shooting electrons of 10 GeV perpendicular to the beam …

Example12 featuring TestEm3-like transport in arbitrary geometry imported from GDML.

---

base/inc/CopCore/include/CopCore/ranluxpp/mulmod.h

This yields single digit percent improvements, depending on the ratio of time spent in the RNG; results are identical.

Use intrinsic for 128 bit multiplication in RANLUX++

---

examples/Example13/example13.cpp
examples/Example13/example13.cu
examples/Example13/example13.h

Implement a simple rotating particle gun that generates flat
distributions in eta and phi between -5 and 5.
This option is off by default.

Add option to distribute particles over eta,phi in example13.

---

examples/Example10/example10.cu

Gammas can do at most one of conversion, Compton scattering, or photoelectric effect and only produce at most one new electron. Also include electrons ionized by positrons (even if they are few).

example10: Fix estimate of nextMaxElectrons

---

examples/Example5/CMakeLists.txt
examples/Example5/example5.cpp
examples/Example5/example5.cu
examples/Example5/example5.h

Geant4 11.0 will require C++17 for (at least some of) its headers. This works fine for all examples that only include them into cpp files because Geant4 automatically switches them to C++17 while CUDA files remain at C++14 - adapt Example5 accordingly.

example5: Split Geant4 initialisation into cpp file

---

base/inc/AdePT/BVHNavigator.h
base/inc/AdePT/LoopNavigator.h
examples/Example10/relocation.cu
examples/Example6/example6.cu
examples/Example7/relocation.cu
examples/Example8/example8.cu
examples/Example9/relocation.cu

With VecGeom compiled using single precision, `kTolerance` is one micrometer and pushing 10um on every boundary crossing creates a measurable systematic error. Thus only push temporarily in the relocation logic and another time in the `ComputeStep` functions, which needed another fix.

Push only temporarily on boundary crossing

---

examples/Example10/CMakeLists.txt
examples/Example10/example10.cpp
examples/Example11/CMakeLists.txt
examples/Example11/example11.cpp
examples/Example6/CMakeLists.txt
examples/Example6/example6.cpp
examples/Example8/CMakeLists.txt
examples/Example8/example8.cpp
examples/Example9/CMakeLists.txt
examples/Example9/example9.cpp
examples/Raytracer_Benchmark/CMakeLists.txt
examples/Raytracer_Benchmark/README.md
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp

I'm getting mad trying to remember which example has `-gdml_name`. The option name chosen by later examples makes more sense to me, use it everywhere.

Use -gdml_file in all examples

---

CMakeLists.txt
examples/Example11/CMakeLists.txt
examples/Example11/example11.cu
examples/Example13/CMakeLists.txt
examples/Example13/example13.cpp
examples/Example13/example13.cu
examples/Example9/CMakeLists.txt

This adds NVTX annotations for example 11 and 13, e.g.
They only have an effect, though, if the executable is linked against NVTX, e.g. by doing:
```bash
cmake -DNVTX=On ...
```

Optional NVTX annotations for example11 and 13

---

base/inc/AdePT/LoopNavigator.h

I forgot this in commit 586a9c4391 ("Improve robustness of navigators"): `RelocateToNextVolume()` must exclude the volume that we just exited from to not accidentally re-enter into it.

Fix oversight in LoopNavigator::RelocateToNextVolume

---

base/inc/AdePT/BVHNavigator.h
base/inc/AdePT/LoopNavigator.h

If `step_limit <= 0`, the step is not limited by geometry and there is no need to ask any solid. In fact, some solids return NaN if passed a `step_max = 0`.

Fix navigation for zero steps

---

examples/Example13/electrons.cu
examples/Example14/electrons.cuh
examples/TestEm3/electrons.cu
examples/TestEm3MT/electrons.cu
magneticfield/inc/fieldPropagatorConstBz.h

Use the safety already available from MSC, and recompute if necessary to avoid querying geometry in multiple chord steps. In combination, the performance improvement for `example13` with `cms2018` and `Bz=1T` is around 27% and more than a factor of 2x for `Bz=3.8T`.
Closes #146

Optimize field propagation with safety

---

CMakeLists.txt

@stognini discovered (and @drbenmorgan confirmed) that AdePT requires VecGeom to be built as static to link correctly. This PR adds a small configure-time check to ensure this is the case. If it fails, it prints a message:
```
CMake Error at CMakeLists.txt:65 (message):
AdePT requires VecGeom to be built a static library, but it is of type
'SHARED_LIBRARY'
```

Add check for VecGeom being built as static library

---

CMakeLists.txt
test/CMakeLists.txt

Currently AdePT does not build/link correctly if the found VecGeom built its CPU library (`libvecgeom`) as a shared library. Because of the dependency between this and the (separate) CUDA library (`libvecgeomcuda`), consumers of either of these libraries must link to both.
This PR fixes builds in `test` that don't do this. Linking is now to both `VecGeom::vecgeom` and `VecGeom::vecgeomcuda_static` with the consuming target built with separable compilation to handle device linking correctly. The static CUDA library is still used to minimise issues with device linking, though support for shared CUDA libraries should be possible after support is available in VecGeom (see: https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/822).
Pinging @sethrj for info.

Support use of VecGeom shared CPU library

---

examples/Example14/src/PhysListHepEm.cc

We now have EM processes for other then e+, e-, gamma particles as in FTFP_BERT (so standard EM). The EM physics for e+, e-, gamma is provided by G4HepEm.

adding em processes for other particles

---

examples/Raytracer_Benchmark/CMakeLists.txt

If an executable uses vecgeom device symbols, i.e. does more than
exclusively deal with vecgeom's c++ interface, it needs to link
statically.
This fixes a failing kernel launch in RaytraceBenchmark.

Link Raytrace benchmark against vecgeomcuda_static.

---

CMakeLists.txt
README.md
examples/Example14/AdeptIntegration.cpp
examples/Example14/AdeptIntegration.cu
examples/Example14/AdeptIntegration.h
examples/Example14/include/DetectorConstruction.hh
examples/Example14/include/DetectorMessenger.hh
examples/Example14/include/EMShowerModel.hh
examples/Example14/macros/example14.mac.in
examples/Example14/src/DetectorConstruction.cc
examples/Example14/src/DetectorMessenger.cc
examples/Example14/src/EMShowerModel.cc
examples/Example14/src/EventAction.cc

In addition, this adds a thorough check for local transformation consistency, comparing each local transformation while crawling in parallel through the Geant4 and VecGeom volume hierarchies. The check is done for both translation  and rotation elements, with a tolerance of 1e-8;
This can only be merged after merging VecGeom [#884](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/884) and bumping the VecGeom tag (to be added in this PR)

Fix for assigning sensitive reflected volumes in Example14

---

examples/Example14/include/DetectorConstruction.hh
examples/Example14/include/DetectorMessenger.hh
examples/Example14/include/EventAction.hh
examples/Example14/macros/example14.mac.in
examples/Example14/src/DetectorMessenger.cc
examples/Example14/src/EMShowerModel.cc
examples/Example14/src/EventAction.cc
examples/Example17/CMakeLists.txt
examples/Example17/include/DetectorConstruction.hh
examples/Example17/include/DetectorMessenger.hh
examples/Example17/include/EventAction.hh
examples/Example17/macros/example17.mac.in
examples/Example17/macros/example17_validation.mac.in
examples/Example17/macros/lhcb_validation.mac.in
examples/Example17/src/DetectorMessenger.cc
examples/Example17/src/EMShowerModel.cc
examples/Example17/src/EventAction.cc

This introduces the command: `/example17/detector/sensitivegroup prefix`  (and the same for example14) allowing to sum-up hits for all placed volumes having the name starting with `prefix`.
Added also 2 new macros in Example17: example17_validation.in and lhcb_validation.in to be used for physics validation

Added sensitivegroup command allowing to group scoring by name prefix.

---

examples/Example14/AdeptIntegration.cpp
examples/Example14/AdeptIntegration.cu
examples/Example14/AdeptIntegration.h
examples/Example14/CommonStruct.h

To make the integration example reproducible, we have to do a full sort of the tracks leaked from the device back to Geant4. This is because the order of the tracks depends on device concurrency, and the random seed sequence on the host depends on the order since it is per CPU thread, not per track.
This change sorts tracks by the product of PDG number, energy, position and momentum components to ensure to a reasonable level the uniqueness of the sorting metric (energy is not sufficient for the gun generator with exa14). 
I am now getting numerically identical results when running multiple times with multiple threads.

Sorting tracks coming from GPU to make integration example reproducible.

---

magneticfield/inc/fieldPropagatorConstBz.h

This error occurred to me now with g++-12 and nvcc 11.7:
```
[ 88%] Building CUDA object examples/TestEm3/CMakeFiles/TestEm3.dir/electrons.cu.o
/home/bgruber/dev/AdePT/magneticfield/inc/fieldPropagatorConstBz.h(139): error: expression must be a modifiable lvalue
detected during:
instantiation of "fieldPropagatorConstBz::Precision fieldPropagatorConstBz::ComputeStepAndNextVolume(double, double, int, fieldPropagatorConstBz::Precision, fieldPropagatorConstBz::Vector3D &, fieldPropagatorConstBz::Vector3D &, const vecgeom::cuda::NavStateIndex &, vecgeom::cuda::NavStateIndex &, __nv_bool &, fieldPropagatorConstBz::Precision, int) [with Navigator=cuda::BVHNavigator]" 
/home/bgruber/dev/AdePT/examples/TestEm3/electrons.cu(112): here
instantiation of "void TransportElectrons<IsElectron>(Track *, …
```

Fix assignment of const variable

---

examples/FisherPrice_Alpaka/CMakeLists.txt

This PR enables the alpaka CUDA backend by default by forcing the cmake CACHE variable `alpaka_ACC_GPU_CUDA_ENABLE` to `ON`.

Enable alpaka CUDA backend by default

---

base/inc/AdePT/NVTX.h

This PR removes a redundancy when setting up and calling `nvtxRangeStartEx`, then adds information about the in-flight particle count to the shown tag at peak occupancy. Finally, I ran clang-format.

Show in-flight particle count at peak occupancy

---

examples/Example19/electrons.cu
examples/Example19/gammas.cu

Adds a lambda function `survive()` which pushes the track back into the active queue.
Running `example19 -particles 10000 -batch 5000 -gdml_file ../examples/Example14/macros/testEm3.gdml` 5x on V100:
before:
Mean: 4.00011
Stddev: 0.00030375
after:
Mean: 4.01492
Stddev: 0.000460478
Output is identical. The slight slowdown is surprising, but it is by far compensated by the subsequent optimizations based on this PR, See #225 and #229.

Mark a track's survival more explicit

---

examples/Example10/example10.cuh
examples/Example11/example11.cuh
examples/Example12/example12.cuh
examples/Example13/example13.cuh
examples/Example14/AdeptIntegration.cuh
examples/Example16/example16.cuh
examples/Example17/AdeptIntegration.cuh
examples/Example18/example18.cuh
examples/Example19/example.cuh
examples/Example5/example5.cu
examples/Example6/example6.cu
examples/Example7/TestEm3.cuh
examples/Example8/example8.cu
examples/Example9/example9.cuh
examples/TestEm3/TestEm3.cuh
examples/TestEm3Compact/TestEm3.cuh
examples/TestEm3DoubleBuffer/TestEm3.cuh
examples/TestEm3MT/TestEm3.cuh

Commit 83836d06bc (https://github.com/apt-sim/AdePT/pull/218) updated G4HepEm and adapted the RNG interface to provide inline implementations instead of function pointers. The intent was to use RANLUX++ on the GPU and continue using the CLHEP generator (MIXMAX by default) on the CPU. However, the CUDA compiler also generates host code for the inline function, which because of symbol interception ends up being used by G4HepEm. This leads to crashes because the inline function assumes to work on an instance of `RanluxppDouble` and just writes to its members, leaving behind an invalid state for CLHEP to seed at the beginning of the next event.
To solve this problem, surround the definition of the inline functions with `#ifdef __CUDA_ARCH__` to only make it visible to the compiler when …

Fix multiple events in integration examples

---

examples/Example13/electrons.cu
examples/Example13/example13.cuh
examples/Example13/gammas.cu
examples/Example14/Track.cuh
examples/Example14/electrons.cuh
examples/Example14/gammas.cuh
examples/Example16/electrons.cu
examples/Example16/example16.cuh
examples/Example16/gammas.cu
examples/Example17/Track.cuh
examples/Example17/electrons.cuh
examples/Example17/gammas.cuh
examples/Example18/electrons.cu
examples/Example18/example18.cuh
examples/Example18/gammas.cu
examples/Example19/electrons.cu
examples/Example19/example.cuh
examples/Example19/gammas.cu
examples/TestEm3/TestEm3.cuh
examples/TestEm3/electrons.cu
examples/TestEm3/gammas.cu
examples/TestEm3DoubleBuffer/TestEm3.cuh
examples/TestEm3DoubleBuffer/electrons.cu
examples/TestEm3DoubleBuffer/gammas.cu

It is beneficial to keep some of the Track members in registers for the duration of the kernel.
Just running `TestEm3` without arguments on my RTX 2060, 5 time mean:
before: 2.67394s
after: 2.61814s
`TestEm3DoubleBuffer`:
before: 2.93838s
after: 2.6724s
Examples with are correct:

Keep some Track members in registers

---

CMakeLists.txt

Following recent changes to VecGeom (see [MR 956](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/956)) testing, the `cms2018` and `trackML` GDML files have changed location. AdePT's configure step didn't pick this up as an empty file was still downloaded so "o.k." but naturally tests then failed.
This PR updates the download URLs to use a recent tag (the GDML file content is near constant anyway) instead of the `master` branch. It also adds the known SHA256 hash of the files to confirm the expected file has been downloaded correctly.

Use fixed tag and hash to download GDML files

---

README.md
scripts/spack.yaml

Provide a minimal spack environment file for providing an environment for AdePT development. Largely identical to that for the Celeritas project for commonality, with some differences:
- Latest AdePT examples require Geant4 11.1, or more specifically, the `Flush()` abstract function of G4VFastSimulationModel.
- AdePT can only be built/used with CUDA, which becomes a hard required spec of the environment and all packages.
Update README with setup instructions for both Spack and the existing LCG `devAdePT` view from CVMFS. Note requirements where known.

Add and document use of Spack environment for development

---

examples/Raytracer_Benchmark/Material.h
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp
examples/Raytracer_Benchmark/RaytraceBenchmark.cu
examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h

VecGeom commit [8359663a](https://gitlab.cern.ch/VecGeom/VecGeom/-/commit/8359663a625c3d6e9fdcd62cbcede1a3b1ca7d68) removed the user hooks in LogicalVolume, which were used in the ray-tracer benchmark for storing custom optical properties. This commit replaces the hooks with an array using volume indices to retrieve the same information.

Fixed raytrace benchmark to work with current VecGeom master

---

base/inc/AdePT/MParray.h
base/inc/AdePT/MParrayT.h

This introduces the `MParrayT<typename T>` type to handle concurrent queues of arbitrary types and not just track indices. Its usage is identical to the current `MParray`, which now becomes an alias for `MParrayT<int>`. 
I'm using this container for a fix of Exa17, where leaked tracks need to be copied by value before the track containers are compacted.

Generalized MParray for arbitrary type.

---

examples/Example17/include/DetectorConstruction.hh
examples/Example17/src/DetectorConstruction.cc

Implemented only in Exa 17, adding in the macro:
`/example17/detector/addsensitivevolume *` will have the effect that all defined sensitive volumes and groups where we score will be ignored, and all volumes in the GPU region will become sensitive

Added possibility to make all volumes sensitive

---

base/inc/CopCore/include/CopCore/Global.h
examples/Example12/example12.cpp
examples/Example13/example13.cpp
examples/Example16/example16.cpp
examples/Example18/example18.cpp
examples/Example19/main.cpp
examples/Example20/main.cpp

This implements  a backend-dependent way (for now just supporting CUDA) to request a different than default stack size on device, and uses it explicitly for the stack-hungry examples. This is needed due to the future removal of altering the stack size in VecGeom, as per this [MR](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/975)

Explicitly increase device stack size for the examples needing it

---

examples/Example17/CMakeLists.txt
examples/Example17/example17.cpp
examples/Example17/include/DetectorMessenger.hh
examples/Example17/include/ParticleGun.hh
examples/Example17/include/PrimaryGeneratorAction.hh
examples/Example17/include/PrimaryGeneratorMessenger.hh
examples/Example17/macros/example17.mac.in
examples/Example17/src/DetectorMessenger.cc
examples/Example17/src/EventAction.cc
examples/Example17/src/ParticleGun.cc
examples/Example17/src/PrimaryGeneratorAction.cc
examples/Example17/src/PrimaryGeneratorMessenger.cc
examples/Example17/src/SteppingAction.cc

* Adds the option to shoot particles uniformly in the chosen Phi/Theta ranges
* Adds the option to define a list of particles to be shot, and choose one at random each time
* Includes a necessary extra check in the SteppingAction for particles going out of the world

Example17 Randomized particle gun

---

examples/Example17/example17.cpp

At least on my system, the compiler warns about the 'missing terminating " character'.

example17: Fix warning about string literals

---

examples/Example12/CMakeLists.txt
examples/Example13/CMakeLists.txt
examples/Example14/CMakeLists.txt
examples/Example15/CMakeLists.txt
examples/Example16/CMakeLists.txt
examples/Example17/CMakeLists.txt
examples/Example18/CMakeLists.txt
examples/Example19/CMakeLists.txt
examples/Example20/CMakeLists.txt
examples/Example21/CMakeLists.txt
examples/Raytracer_Benchmark/CMakeLists.txt
test/CMakeLists.txt

When included as a subproject as `add_subdirectory` or similar, the `CMAKE_{SOURCE,BINARY}_DIR` variables will point to those of the highest level project. This will not be the same as the root of the AdePT source code. Include/etc paths will not then be correct, leading to compile time errors. Additionally, generated files may appear in the wrong place, or clash with higher level projects. This _may_ be one of the methods experiments use to integrate the code, so good to support it, and will also help co-working with Celeritas.
Use `PROJECT_{SOURCE,BINARY}_DIR` in place of the `CMAKE_` versions to guarantee pointing to the AdePT root source/build directories.

Use `PROJECT_{SOURCE,BINARY}_DIR` in place of `CMAKE_` equivalent

---

CMakeLists.txt

When trying to configure with Geant4 11.1, G4HepEm seems to have problems finding Geant4 even though AdePT's correctly found it before. As a reason, CMake quotes not finding XercesC even though both Vecgeom and Geant4 (searched from AdePT) find it. It seems explicitly looking for XercesC solves the problem (not sure why).

[cmake] Fix configuration with Geant4 11.1

---

external/CMakeLists.txt
test/CMakeLists.txt
test/test_g4vg_link.cpp

As discussed at the last AdePT/Celeritas standup, and for this afternoon's hackathon, this shows the _minimal_ steps for use of [celeritas-project/g4vg](https://github.com/celeritas-project/g4vg) in AdePT. This is just:
1. Use of `FetchContent` to get the code and add it to the build
2. A smoke test of including the `G4VG.hh` public header and linking to `libg4vg`
It's been tested on a centos9 with gcc11/cuda12 and seems to build and run o.k., but it is trivial!
Also pinging @sethrj for info/double check.

Minimal fetch and use of G4VG for in-memory Geant4<->VecGeom conversion

---

CMakeLists.txt
examples/CMakeLists.txt
examples/Example1/CMakeLists.txt
examples/IntegrationBenchmark/CMakeLists.txt
test/CMakeLists.txt
test/TestEm3/CMakeLists.txt
test/testField/CMakeLists.txt

This is a purely cosmetic cleanup of the CMake scripts to assist in the next stage of trying to simplify the library structure and linking. Split here to avoid too much in one go. There should be no changes to build or test behaviour.

Minimal tidy of CMake scripts

---

examples/Example1/src/DetectorConstruction.cc
include/AdePT/core/AdePTConfiguration.hh
include/AdePT/integration/AdePTTrackingManager.hh
src/AdePTPhysics.cc
src/AdePTTrackingManager.cc

Previously AdePTTransport was initialized at AdePTPhysics::ConstructProcess. However at this point the material-cut couples are not yet initialized in Geant4, which means G4HepEM can't be initialized. The workaround was to manually initialize them in the user detector construction.
This PR delays the AdePT initialization until AdePTTrackingManager::BuildPhysicsTable, at which point we have all the information we need.
One downside of this approach is that now we have a pointer to AdePTConfiguration in AdePTTrackingManager, rather than AdePTPhysics being the only user of the configuration.

Moving AdePT Initialization to AdePTTrackingManager::BuildPhysicsTable

---

.clang-format
CMakeLists.txt
include/AdePT/base/MParrayT.h
include/AdePT/benchmarking/NVTX.h
include/AdePT/copcore/CopCore.h
include/AdePT/copcore/Global.h
include/AdePT/copcore/Macros.h
include/AdePT/copcore/PhysicalConstants.h
include/AdePT/copcore/VariableSizeObj.h
include/AdePT/kernels/electrons.cuh
src/AdePTTrackingManager.cu

While rebasing the AsyncExample onto master, I found the following items:
- fixed some compiler warnings
- fixed a link error with cuda
- worked around the "ptx assembly failed" bug in cuda < 12.6 (I reported it to NVidia, and that's the first version where it will be fixed)
- Corrected a few docstrings
- And removed `-G` from `RelWithDebInfo`
I cherry-picked them out of the branch to share them already now.

Various small updates

---

CMakeLists.txt

This changes the include path on the `AdePTTargets.cmake` file from `/include/[AdePT|Copcore]` to `/include/`

Fix wrong include path on exported targets file

---

examples/Example1/macros/example1_ttbar.mac.in
include/AdePT/integration/AdePTTrackingManager.hh
src/AdePTTrackingManager.cc

- Improves the GPU region check while stepping a track by changing from a linear search to using a set
- Only check when the region changes
- If there are no GPU regions registered, give the track back to Geant4's default tracking manager

Improving GPU region check

---

examples/IntegrationBenchmark/src/TrackingAction.cc
include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/HostScoringStruct.cuh
include/AdePT/core/Track.cuh
include/AdePT/core/TrackData.h
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

AdePT tracks were previously not storing any track ID. With this change we will propagate the ID of particles coming into AdePT to their secondaries. This ID is added to the hit information returned to Geant4.
In addition to the hits, the ID is also set as the mother for leaked particles.

Keeping track of original particle ID

---

test/CMakeLists.txt

This is needed because g4vg pulls in almost the full Celeritas library, which maintains an old version of the interfaces to the surface model, not compiling anymore.
Without this PR we cannot work on updating the integration of the VecGeom surface model.

Disabled g4vg when VecGeom is compiled with the surface model

---

include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/HostScoringStruct.cuh
include/AdePT/core/Track.cuh
include/AdePT/core/TrackData.h
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp

This changes PR [296](https://github.com/apt-sim/AdePT/pull/296) to pass the propagated primary ID as parentID for the hits generated by AdePT.
It also fixes an issue during track reconstruction on the CPU side where some vectors wouldn't be properly initialized

Original particle ID used as ParentID for the hits

---

src/AdePTGeant4Integration.cpp

This fixes the wrong logic in FillG4NavigationHistory and adds the missing MaterialCutsCouple pointer in the 'fake' step reconstructed from AdePT information and used to call the G4 sensitive detectors.

 FillG4NavigationHistory fix

---

examples/Example1/CMakeLists.txt
examples/Example1/macros/example1_ttbar_noadept.mac.in
src/AdePTTrackingManager.cc

- Avoids calling the AdePT Shower function during the event flush if there are no particles in the AdePT buffer. The time spent in this extra call is specially noticeable when using small events.
- Adds a macro file to use with the `--noadept` option in `example1`

Fix: Don't call flush for an empty buffer

---

examples/Example1/example1.cpp
examples/Example1/include/DetectorConstruction.hh
examples/Example1/src/DetectorConstruction.cc

Adds the option `--allsensitive` for example 1 so that the SD information in the geometry will be ignored and all volumes marked as sensitive.
This mode is useful in order to quickly validate geometries which don't contain SD info.

Adding option to set all volumes as sensitive

---

examples/Example1/include/SensitiveDetector.hh
examples/IntegrationBenchmark/include/SensitiveDetector.hh

With GCC 11.4 AdePT doesn't compile because it misses set in the `SensitiveDetector`

include set

---

examples/Example1/include/SensitiveDetector.hh
examples/IntegrationBenchmark/include/SensitiveDetector.hh
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/HostScoringStruct.cuh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/magneticfield/fieldPropagatorConstBz.h
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h
include/AdePT/navigation/SurfNavigator.h
src/AdePTGeant4Integration.cpp
test/testField/electrons.cu
test/testField/gammas.cu

The AdePT interfaces for navigation normally compute first the distance to the next hit volume, then relocates to find out the next path. The first interface for surface navigation did systematically step+relocation in one go, which is very inefficient in case of non-zero magnetic field, where the field propagator has to call the distance computation in several points along the trajectory.
The PR introduces the split: distance computation does not change the output state, but sets its boundary flag according to a surface being hit within the physics step, returning also the index of this surface. The relocation method used this index as input. Due to the addition of this index in the interfaces, currently, the calling interface of the surface navigator is for the moment different than the …

Surface navigation now split in finding the frame and relocation

---

examples/Example1/CMakeLists.txt
examples/Example1/macros/example1.mac.in
examples/Example1/macros/example1_large_stack.mac.in
examples/Example1/macros/example1_ttbar.mac.in
examples/Example1/macros/example1_ttbar_LHCb.mac.in
include/AdePT/core/AdePTConfiguration.hh
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/integration/AdePTConfigurationMessenger.hh
src/AdePTConfigurationMessenger.cc
src/AdePTTrackingManager.cc

- Fix for the copy of the surface model to GPU, which was being called from all threads
- Removed the hardcoded device stack limit and added a configuration option in the macro
- Added the line `SET(CMAKE_EXE_LINKER_FLAGS "-Wl,--disable-new-dtags")` to `Example1/CMakeLists.txt` which solves an issue where Geant4 libraries would not be properly linked in some systems

GPU geometry transfer fix and stack limit configuration option

---

src/AdePTGeant4Integration.cpp

Fixes a memory leak caused by the instantiation of vectors while reconstructing tracks from GPU data, which were never deallocated.

Fix memory leak in scoring

---

CMakeLists.txt
examples/Example1/CMakeLists.txt
examples/IntegrationBenchmark/CMakeLists.txt
include/AdePT/benchmarking/TestManager.h
include/AdePT/core/AdePTConfiguration.hh
include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AdePTTransportStruct.cuh
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/HostScoringStruct.cuh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/integration/AdePTPhysics.hh
include/AdePT/integration/AdePTTrackingManager.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTConfiguration.cc
src/AdePTGeant4Integration.cpp
src/AdePTPhysics.cc
src/AdePTTrackingManager.cc
src/AdePTTransport.cc
src/AdePTTransport.cu
test/CMakeLists.txt

- Add an interface for switching between different AdePT backends. In this way, the AsyncAdePT implementation can share scoring and integration code with example1.
- Split the transport from the integration-related parts by creating a
new library.
- Create a transport abstraction, so AdePTTrackingManager is independent
of the transport implementation.
- Add thread and event IDs to the transport interface. These are
necessary for the async transport implementation.
- Start to enumerate tracks in the tracking manager. This can be used to
reproducibly seed the AdePT random sequences.
- Add some const declarations for the default AdePT implementation.
- Use a factory funciton to instantiate AdePT. Like this, different
AdePT implementations can be used without changing code in the tracking …

Create a transport interface for switching between AdePT implementations

---

src/AdePTGeant4Integration.cpp

If a step was recorded at the edge of the world such that the NextState would be "outside"  the reconstruction algorithm would try to access a outside volume that doesn't exist in the lookup table. This would lead to a segfault.
This PR adds a safeguard against that case. The scenario is unrealistic in a real setup, but should be avoided for stability (and the error was observed in some small tests)

[mini] fix bug if next state was outside

---

examples/AsyncExample/include/SensitiveDetector.hh
examples/AsyncExample/src/SensitiveDetector.cc
examples/Example1/include/SensitiveDetector.hh
examples/Example1/src/SensitiveDetector.cc
examples/IntegrationBenchmark/include/ActionInitialisation.hh
examples/IntegrationBenchmark/include/RunAction.hh
examples/IntegrationBenchmark/include/SensitiveDetector.hh
examples/IntegrationBenchmark/integrationBenchmark.cpp
examples/IntegrationBenchmark/src/ActionInitialisation.cc
examples/IntegrationBenchmark/src/EventAction.cc
examples/IntegrationBenchmark/src/RunAction.cc
examples/IntegrationBenchmark/src/SensitiveDetector.cc
src/AdePTGeant4Integration.cpp

This PR fixes a major memory corruption problem in the scoring:
Previously, the + 1 here:
```
::new (toucheableHandleStorage) G4TouchableHandle{::new (toucheableHistoryStorage + 1) G4TouchableHistory};
```
Was a too small offset. Thus, the `fPostG4TouchableHistoryHandle` overlapped with the `fPreG4TouchableHistoryHandle` and overwrote its values. This is now fixed. The error broke the physics validation (note: the physics validation was done using the latest version of G4HepEm which will be made available via #324):
Before this PR:
(the absolute scale here is off due to a change in the number of particles that was not incorporated into the plot, the relative error is correct)
After this PR:
Additionally, some quality of life improvements are added:
1. The way of accessing the correct ID …

fix memory corruption in scoring

---

examples/common/include/ParticleGun.hh
examples/common/src/ParticleGun.cc

This PR slightly re-designs the AdePT `ParticleGun`. Previously, it was derived from the `G4ParticleGun` and used its own `ParticleGunMessenger`. However, even if the `ParticleGunMessenger` was derived from the `G4ParticleGunMessenger` (currently it is derived from the `G4UImessenger`) this approach is flawed, since the original `G4ParticleGunMessenger` attached to the `G4ParticleGun` that is invoked when the derived AdePT `ParticleGun` is instantiated is *not* attached to the AdePT `ParticleGun`. That meant that the default commands such as `/gun/position` would not work and just be ignored.
This is fixed by instead of deriving the AdePT `ParticleGun` from the `G4ParticleGun`, it has a member `fG4ParticleGun`. This member has then attached the original `G4ParticleGunMessenger` that takes …

fix particle gun

---

include/AdePT/core/HostScoringImpl.cuh

This PR fixes a critical bug in the HostScoring implementation:
The 3 variables required for the next hit slot
```
hostScoring_dev->fBufferStart        = 0;
*(hostScoring_dev->fNextFreeHit_dev) = 0;
*(hostScoring_dev->fUsedSlots_dev)   = 0;
```
were not reset between events. Although they were ever increased via `  unsigned int next = hostScoring_dev->fNextFreeHit_dev->fetch_add(1);` (and the `fBufferStart` was set to be the `fNextHitFree`), it worked due to the circular nature of the buffer `return next % hostScoring_dev->fBufferCapacity;`. However, as soon as the maximum int was exceeded, the simulation would simply stall and not do anything else anymore. This PR fixes that by resetting the three variables between events using a new function `ResetBufferStatsGPU`.
Note that there are a …

reset buffer stats in HostScoring

---

CMakeLists.txt
examples/Example1/example1.cpp
examples/IntegrationBenchmark/include/ActionInitialisation.hh
examples/IntegrationBenchmark/integrationBenchmark.cpp
examples/common/src/FTFP_BERT_AdePT.cc
examples/common/src/FTFP_BERT_HepEm.cc
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/Track.cuh
include/AdePT/core/TrackData.h
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/integration/AdePTPhysics.hh
include/AdePT/integration/AdePTTrackingManager.hh
include/AdePT/integration/G4HepEmTrackingManagerSpecialized.hh
include/AdePT/integration/HepEMPhysics.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/kernels/gammas_split.cuh
src/AdePTPhysics.cc
src/AdePTTrackingManager.cc
src/G4HepEmTrackingManagerSpecialized.cc
src/HepEMPhysics.cc
test/testField/electrons.cu
test/testField/gammas.cu

This PR introduces the required changes needed to use the latest version of G4HepEm. In G4HepEm the representation for the cross sections changed in this [PR](https://github.com/mnovak42/g4hepem/pull/115). Additionally, the e-+/gamma-nuclear reactions were added in G4HepEm. 
This PR
1.  uses the new function `G4HepEmGammaManager::SampleInteraction` and fixes the numIALeft.
**_Note_**: that since we don't register the gamma/lepton nuclear processes in the physics list they are currently ignored by AdePT and G4HepEm.
2. adopts the TrackingManager approach by using a derived class of the G4HepEmTrackingManager. This supersedes #316. The G4HepEmTrackingManagerSpecialized is instantiated as a member of the AdePTTrackingmanager and it takes care of all CPU propagation and cleans up the …

upgrade to latest G4hepem

---

include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/Track.cuh

Unfortunately #324 missed to add the initialization of the new component of `numIALeft` which led to non-reproducible results as soon the the circular buffer got around, found in a long discussion with @hahnjo.
To Do:
Validation: 
`setTrackInAllRegions`:
`alllayers`:
`regions`:
`noregions`

fix uninitialized values

---

examples/Example1/src/EventAction.cc
examples/Example1/src/RunAction.cc
examples/Example1/src/TrackingAction.cc
examples/IntegrationBenchmark/src/EventAction.cc
examples/IntegrationBenchmark/src/Run.cc
examples/IntegrationBenchmark/src/TrackingAction.cc
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/integration/AdePTGeant4Integration.hh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc
test/testField/testField.cpp

In the hunt for some ugly non-reproducibility bug, I used strict compiler settings with `add_compile_options(-Wall -Wextra -Werror -Wuninitialized)`
This PR cleans unused variables and incorrect types that don't have any effect but prevent the usage of strict compiler settings.

fix minor things for strict compiler settings

---

examples/CMakeLists.txt
examples/IntegrationBenchmark/CMakeLists.txt
examples/IntegrationBenchmark/ci_tests/python_scripts/check_validation.py
examples/IntegrationBenchmark/ci_tests/reproducibility.sh
include/AdePT/kernels/gammas.cuh

This updates the gamma kernel, which is a leftover from #324.
The `SampleInteraction` only needs to be called if no boundary is hit (as otherwise no physics process is used). This enables to keep the `numIALeft` which is stored in the `currentTrack` and needs to be passed to the G4HepEm theTrack. The previous early exit with setting the winnerprocess to -1 caused non-reproducibility.
Since the code is reproducible with this fix, the CI test for reproducibility with 8 ttbar events in CMS (no B field) is activated and replaced the previous test that just ran one event. 
To do:
Physics validation results are just as before:
allGPUregion:
some layers as GPU region:

Update gamma kernel, add reproducibility CI test

---

include/AdePT/integration/AdePTPhysics.hh
include/AdePT/integration/HepEMPhysics.hh

This fixes the `AdePTPhysics` and `HepEmPhysics` in AdePT, to have the same default values as the class they are derived from: `G4EmStandardPhysics`. This allows for using a factory function and is required in Gauss for LHCb simulations.

[mini] fix constructors for AdePTPhysics

---

include/AdePT/core/Track.cuh
include/AdePT/kernels/electrons.cuh
include/AdePT/magneticfield/fieldPropagatorConstBz.h
include/AdePT/navigation/SurfNavigator.h

Implementing two safety features:
1. Safety caching: the tracks hold the point where safety is computed, and the safety value in that point. When safety is needed in a different point, the method track.GetSafety(new_point) will subtract from the cached value and return the positive remainder or zero otherwise. The GetSafety method can take an accurate limit value, and when the remainder is smaller than this limit the returned safety is zero. It is the user responsibility to call track.SetSafety(pos, safety) whenever the safety is fully recomputed in a new position.
2. Safety calculation uses a new surface model feature only to compute safety accurately when close to boundaries, and only use the aligned bounding box safety when far away. The distance limit is passed as a third parameter to …

Better use of safety.

---

src/AdePTTrackingManager.cc

This move the InitializeApplyCuts to the BuildPhysics, as in Gauss the ApplyCuts flag was set separately and not yet available at the stage of PreparePhysics.

move InitializeApplyCuts

---

examples/common/src/FTFP_BERT_AdePT.cc
examples/common/src/FTFP_BERT_HepEm.cc
include/AdePT/integration/AdePTPhysics.hh
include/AdePT/integration/HepEMPhysics.hh
src/AdePTPhysics.cc
src/HepEMPhysics.cc

Reverting the base class for AdePTPhysics and HepEMPhysics to G4VPhysicsConstructor. The constructors were transparently constructing G4EmStandardPhysics, G4EMStandard is now registered on the physics list again.

Reverting base class of physics constructors

---

include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh

The sync and async modes differ only on how the GPUHit slot is retrieved, this PR unifies the rest of the code in the `FillHit` call
Also, improve the RecordHit interface by passing references instead of pointers.

Unify common part of RecordHit

---

CMakeLists.txt
cmake/AdePTConfig.cmake.in
examples/Example1/CMakeLists.txt
examples/Example1/macros/example1_large_stack_g4vg.mac.in
include/AdePT/integration/AdePTGeant4Integration.hh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc
test/CMakeLists.txt

This supersedes #289 to integrate the now standalone celeritas-project/G4VG library into AdePT for in-memory geometry conversions without an intermediate GDML file. The as-submitted implementation is:
- G4VG is pulled in via CMake's `FetchContent` mechanism to build it as part of AdePT.
- It is linked in to the AdePT integration library
- `AdePTGeant4Integration::CreateVecGeomWorld(G4VPhysicalVolume const *physvol)` is implemented to use G4VG to do the in-memory conversion.
- `AdePTTrackingManager::InitializeAdePT()` is updated to use that function _if_ `AdePTConfiguration::fVecGeomGDML` is empty.
- An extra test of example1 is provided that is identical to the existing test, except for not setting `AdePTConfiguration::fVecGeomGDML`.
- I've confirmed locally that this results in the in …

Integrate G4VG for use of in-memory conversion of Geant4->VecGeom geometries

---

include/AdePT/core/AdePTTransport.icc
include/AdePT/integration/AdePTGeant4Integration.hh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

For consistency, we now use a vector for mapping vecgeom PlacedVolume IDs to Geant4 Physical volumes, as provided by g4vg.
For the time being we also generate this mapping on AdePT side rather than using the G4VG-provided map as there are a small number of volumes with different mappings when using either method.

Using g4vg-style placed volume map when loading geometry from GDML

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/PerEventScoringImpl.cuh

This PR passes the debug levels properly to the async particle transport again, now `adept/verbose` yields good debug printouts in the async mode.
The handling of the GPUsteps is improved: instead of copying out the full vector and making a shared pointer from each thread point to it (this could cause issues if one worker was already done with its work, not releasing the buffer), now just the steps that need to be processed by that worker are copied to the queue of that worker.
Note that this is not the final implementation, since it is still too slow and the GPU can easily run out of hitslots because the buffer is not ready yet to be swapped back in, therefore a helper function is left in the code and a few changes are not done to allow for flexibility to test out the other approaches. …

Improve async memory usage

---

include/AdePT/core/AsyncAdePTTransport.icc

Removes the per-integration object call to `InitScoringData` for the async mode. The volume map is now a static member initialized at `CreateVecGeomWorld`, so it's shared by all threads.

Remove scoring initialization call for async mode

---

test/CMakeLists.txt

Reported by @SeverinDiederichs, trying to build AdePT with a static VecGeom results in a failure of the `test_g4vg_link` buildtime test. This wasn't spotted in the initial PR because my setup had used a _shared_ build of VecGeom. The underlying cause is likely a corner case in `cuda_rdc_target_link_libraries` not linking in everything from VecGeom in the right order, or failing to do a final device link in the static case. This does not affect linking of AdePT itself with VecGeom and G4VG, where the explicit links to the VecGeom libs are done in the same way as this fix.
Use direct call to target_link_libraries for the G4VG link test, explicitly linking to both G4VG and the Vecgeomcuda targets. This gives a correct link whether VecGeom was built with static or shared libs, and matches …

Use direct linking to vecgeom's CUDA target to match AdePT

---

include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/CommonStruct.h
include/AdePT/core/Track.cuh
include/AdePT/core/TrackData.h
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/integration/AdePTTrackingManager.hh
include/AdePT/kernels/electrons.cuh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

This is part of the modifications required to run AdePT in ATLAS Athena. With this PR we keep track of the origin touchable of each track, as implemented [here](https://github.com/mnovak42/g4hepem/pull/108/commits/80340477d82b82fda678edf67c7081e5c7ba88f3) for the `G4HepEmTrackingManager`.
The main modifications needed for this are:
- Adding a new `NavigationState` field to AdePT tracks to store the origin touchable
- Convert the track's origin touchable to a VecGeom `NavigationState` when it goes into a GPU region
-  When a primary track starts directly in a GPU region it's origin touchable is not set, so we take the track's current position
- The origin is set for particles generated during GPU transport
- When particles leak back to G4, reconstruct the origin touchable and add it to the …

Storing the origin touchable of each track

---

CMakeLists.txt
cmake/AdePTConfig.cmake.in

A small ease of use/integration enhancement to use an external install of G4VG by default, falling back to use of `FetchContent` otherwise.
This should allow easier integration in ATLAS/Athena as well as common integration with Celeritas so the same G4VG install is used without symbol clashes.

Provide option to select between G4VG via FetchContent or find_package

---

CMakeLists.txt
examples/IntegrationBenchmark/ci_tests/example_template.mac
src/AdePTGeant4Integration.cpp

Enables the new G4VG option to avoid using VecGeom's reflection factory (https://github.com/celeritas-project/g4vg/pull/22), which solves the wrong mapping of the daughters of reflected volumes in G4VG's PlacedVolume ID to G4 physical volume map.
Note that since we don't build the map on AdePT side anymore this change is incompatible with any previous G4VG commits.

Using G4VG's PlacedVolume map

---

include/AdePT/kernels/electrons.cuh

The solid model relies on small pushes to relocate to the next volume. If on boundary, by default it pushes by 1e-8, which is too small to help some stuck particles. A push of 1e-8 can easily lead to no push at all in one direction, which might be the direction where the push is needed. This PR sets the push value to 1e-6 (`1e3 * kTolerance`) by default, making it much more stable and preventing stuck particles that were observed in the HGCAL.

use a push in the solid model

---

examples/IntegrationBenchmark/ci_tests/reproducibility.sh
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/CommonStruct.h
include/AdePT/core/Track.cuh
include/AdePT/core/TrackData.h
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

As part of the modifications required to run AdePT in ATLAS Athena, with this PR we keep track of vertex information needed by some user codes in Athena, mirroring this change in the G4HepEM tracking manager: https://github.com/mnovak42/g4hepem/pull/108/commits/b3dc506679424e0814c67b75612863bd25e44aba
As in the previous Athena-related PR https://github.com/apt-sim/AdePT/pull/347, we don't pass this information for scoring yet, but this can be done if eventually needed.
Performance test for these additions:
`CMS2018, 32 TTbar, 8 Threads, Transport on ECAL+HCAL`
|        | Sync    | Async   |
|--------|---------|---------|
| Master | 305.363 | 284.428  |
| New    | 308.255 | 283.359 |
`TestEm3, 128 events, 100x10GeV e-`
|        | Sync    | Async   |
|--------|---------|---------|
| Master …

Storing vertex information

---

CMakeLists.txt
src/AdePTGeant4Integration.cpp

The latest updates to G4VG allow Geant4 parametrised/replica volumes to be converted to a VecGeom representation by direct placements. The need for this comes from the Delta Assessment "B5" example that uses these structures and for which there is no direct VecGeom equivalent except by making a direct placement for each copy. That's supported as of [G4VG 1.0.3](https://github.com/celeritas-project/g4vg/releases/tag/v1.0.3), but using this in AdePT and trying out B5 still leads to errors from `AdePTG4Integration::visitGeometry`.
That's sort of expected as the translation between Geant4 and VecGeom means that there will be N VecGeom placements for each replicated volume, N corresponding to the total number of replicas. Consequently, the checks in `visitGeometry` fail as:
1. The number of …

Handle converted G4VPVParameterised/G4PVReplica volumes from G4VG in geometry checks

---

include/AdePT/core/AdePTConfiguration.hh
include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/integration/AdePTConfigurationMessenger.hh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/integration/AdePTTrackingManager.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTConfigurationMessenger.cc
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

If the UserSteppingAction is required, we need to copy back every GPU step back to the G4 workers. 
This required to change the kernels, as we need to be able to record every step independent of edep or sensitive detector. 
Since copying back every step can lead to a very large amount of steps, this would quickly fill the buffer. Then, if the buffer gets too full before the Geant4 workers take care of their hits, the GPUStep Management Thread would start copying out the GPUSteps, as implemented in #350. However, this copying is too slow, if every Step is recorded and leads to the GPU running out of HitSlots. 
Previously, the Geant4 workers would only take care of the GPU Steps after their transport has finished. However, this may be too late and the buffer may be too full, leading to …

enable calling of UserSteppingAction and PostUserTrackingAction

---

src/AdePTGeant4Integration.cpp
test/CMakeLists.txt
test/test_g4vg_link.cpp

A minor cleaning PR that removes the error-prone name check (which is triggered in FullSimLight) and the G4VG linking test, as we now build it directly.

remove error-prone name check and G4VG linking test

---

include/AdePT/core/AdePTConfiguration.hh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/AsyncAdePTTransportStruct.cuh
include/AdePT/integration/AdePTConfigurationMessenger.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTConfigurationMessenger.cc

This PR introduces a new feature for the async mode: `/adept/FinishLastNParticlesOnCPU`.
It is not complete yet, as they are currently just killed and not pushed to the CPU, as this will require #358 to work and be merged.
Still, killing the last N particles can currently be used to assess some performance bottlenecks with the magnetic field.
Also, a timer is added to the printout of the async printouts.
This allows for the plotting the numbers of flight vs time and not just only vs iterations, as this severely skews it towards the fast iterations at the tail:

Enable event finishing

---

include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/CommonStruct.h
src/AdePTTrackingManager.cu

Previously, sync AdePT was not passing the debug level, so no output depending on `/adept/verbose` could be generated.
This is fixed in this PR. Furthermore, the time and eventId is printed, which is useful to get plots like these:

[mini] Improve sync AdePT output

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.icc

For some corner cases, where EM only and single particle events are used, the EventState jumps from `G4RequestsFlush` past the `InjectionCompleted` although the injected particle was not yet visible on the device. That led to the event getting closed as the particles in flight were 0, and the particle was then associated with the next event, leading to energy deposition in the next event.
This HotFix is just a fast solution to this problem. The injection state can only go to InjectionCompleted after 25 (hardcoded number) iterations. This requires proper fixing in the future.

hotfix for injection in Async AdePT

---

examples/Example1/src/RunAction.cc
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp

Set the step status if on a boundary. 
This change should be paired in the future with returning all steps done in sensitive volumes, even if they don't deposit any energy.

Setting step status when on boundary

---

examples/Example1/src/DetectorConstruction.cc
examples/IntegrationBenchmark/src/DetectorConstruction.cc
include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportStruct.cuh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/AsyncAdePTTransportStruct.cuh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/kernels/electrons.cuh
src/AdePTGeant4Integration.cpp

Previously, only a constant Bz field was available.
As needed for the B5 example, a full uniform magnetic field is required. There was an not-up-to-date analytical Bany field integrator. Since it was not up to date, here I propose to simply use the RK integrator.
Now, similar to the GeneralMagneticField, a UniformMagneticField is created on the host, and passed to the device.
This cleans up quite a bit of logic on the B field.

enable full uniform B field via RK integrator

---

include/AdePT/core/AdePTConfiguration.hh
include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/integration/AdePTConfigurationMessenger.hh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTConfigurationMessenger.cc
src/AdePTGeant4Integration.cpp

This PR fixes multiple issues:
Now, the `PreUserTrackingAction` is also called. The Flag is renamed from `/adept/CallPostUserSteppingAction` to `/adept/CallUserSteppingAction`. Note, since we currently do not pass the steps done in G4 to the GPU, this works only if we track everywhere.
An early return for if nextstate outside was removed from the gamma kernel as it is needed to calculate the energy leak.
The ekin is set correctly for leaking positrons. The ekin is corrected for stopped electrons.

Enable PreUserTrackingAction and fixes related to leaked energy

---

CMakeLists.txt
include/AdePT/core/PerEventScoringImpl.cuh

This mini PR removes an unused CMake option and adds an include. If run with an older VecGeom version, the include was missing and the code wouldn't compile.

Mini cleaning

---

include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/CommonStruct.h
include/AdePT/core/Track.cuh
include/AdePT/core/TrackData.h
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

Part of the modifications required to run AdePT in ATLAS Athena, mirrors this change in G4HepEM: https://github.com/mnovak42/g4hepem/pull/108/commits/0d57bd8b4f6dfb9a73052689bd54338e377d6fe4
`CMS2018, 32 TTbar, 8 Threads, Transport on full detector`
|        | Sync    | Async   |
|--------|---------|---------|
| Master | 291.489 | 151.281 |
| New    | 290.848 | 151.887 |

Propagating track weight inside AdePT

---

include/AdePT/core/AsyncAdePTTransport.cuh

That call used the wrong variable, leading to far out of bounds accesses

fix out of bounds access

---

test/regression/CMakeLists.txt

This mini PR fixes a minor hiccup from #373 :
The copying of the gdml was flawed, if one tried to reconfigure the cmake config (e.g., switching from `-DASYNC_MODE=ON` to `OFF`) it would fail with:
```
CMake Error at test/regression/CMakeLists.txt:27 (file):
file COPY cannot copy file
"/home/ndiederi/software/AdePT/examples/data/testEm3.gdml" to
"/home/ndiederi/software/AdePT/adept-build/testEm3.gdml/testEm3.gdml": Not
a directory.
```
This PR fixes it by using the directory as destination and not the file itself.

[mini] fix gdml copy

---

CMakeLists.txt
include/AdePT/core/AdePTConfiguration.hh
include/AdePT/integration/AdePTConfigurationMessenger.hh
include/AdePT/kernels/electrons.cuh
src/AdePTConfigurationMessenger.cc
src/AdePTPhysics.cc

This PR makes the multiple steps and energy loss fluctuations in G4HepEm configurable from within AdePT.
Now, those are run time and not compile time options.
When turning off the multiple steps in G4HepEm, AdePT and G4HepEm show below 0.04% agreement:
As the default parameters were fixed for G4HepEm, one comparison (previously to < 0) needed to be fixed. Furthermore, a few UI commands were fixed that required to fetch the boolean value.

Make energy loss and multisteps in MSC with transportation configurable

---

src/AdePTTrackingManager.cc

In the experimental frameworks, AdePT must be initialized by the G4 workers, because at the initialization time of the master thread, the number of G4 workers is not yet known.
Therefore, the initialization is postponed to the first G4 worker. Then, all other G4 workers must wait for the first worker to have initialized AdePT before they can proceed.
This fixes running with AdePT in Gauss and Athena.

Initialize AdePT from G4 workers

---

CMakeLists.txt
examples/data/testEm3_regions.gdml
include/AdePT/core/AdePTConfiguration.hh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/AsyncAdePTTransportStruct.cuh
include/AdePT/core/CommonStruct.h
include/AdePT/integration/AdePTConfigurationMessenger.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTConfigurationMessenger.cc
src/AdePTGeant4Integration.cpp
src/G4HepEmTrackingManagerSpecialized.cc
test/regression/CMakeLists.txt
test/regression/IntegrationTest/src/RunAction.cc
test/regression/scripts/example_template.mac
test/regression/scripts/python_scripts/macro_generator.py
test/regression/scripts/reproducibility.sh
test/regression/scripts/reproducibility_regions.sh
test/regression/scripts/validation_testem3.sh
test/regression/scripts/validation_testem3_regions.sh

This fixes the extraction of leaked tracks in Async mode. The previous extraction of leaks didn't work in most cases for two main reasons:
- The size of the buffer used for extracting the leaked tracks is limited, so if there are too many, the extraction needs to be done in multiple steps. However, there was no mechanism to do this, tracks would get postponed until the next extraction step, but the corresponding events were notified that all leaks had been extracted. This means that whenever the number of leaks exceeded the buffer size the overflow was lost.
- There wasn't a way to guarantee that all leaks corresponding to the event requesting a flush had been extracted. The tracks are not extracted in order of insertion, and the transport kernels were allowed to insert new tracks into …

Fix leaks in asynchronous mode

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransportStruct.cuh

Currently async mode uses one slotmanager, and one array for tracks, the slotmanager keeps track of the usage of the track array, handing out free slots and doing cleanup when necessary, and we keep per-particle lists of slots occupied by that particle type. With this change, each particle type has it's own slotmanager and array of tracks.
This is needed in order to implement the split kernels in async mode, since in that case, in addition to the AdePT tracks we also keep G4HepEM tracks, which need to be per-particle (This means that we cannot keep all hepem tracks in the same array as we do with AdePT tracks)
In addition to that, this will allow for better coalesced memory operations when using split kernels, as the loaded tracks will be more contiguous in memory.

Separating slot manager into per-particle managers

---

include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/core/Track.cuh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp

This PR fixes the global time in the scoring, as it is now passed back to Geant4. Also, a bug is fixed: for calculating the global time, the initial velocity must be used, before updating the kinetic energy due to energy loss. Before, stopped particles would then lead to an infinite global time. Now it conforms with G4.
The globalTime for secondaries is also corrected: before it was taking the globaltime from `currentTrack`, however, the member `currentTrack.globalTime` was only updated in survive, so after the secondary was created. Now the current globalTime is passed to the constructor.
Now, the time seems to be fully correct in the Gauss histograms

Fix global time in scoring

---

CMakeLists.txt
examples/Example1/src/EventAction.cc
include/AdePT/copcore/Ranluxpp.h
include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/Track.cuh
include/AdePT/core/TrackDebug.cuh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h

A `uint_64` number is generated from the track seed at construction time. As long as the seed sequence is reproducible and non-clashing, so are the track id's.
To enable debugging of track N in the step range MIN-MAX: configure with ADEPT_TRACK_DEBUG=1; run like: ADEPT_DEBUG_TRACK=N ADEPT_DEBUG_MINSTEP=MIN ADEPT_DEBUG_MAXSTEP=MAX <executable> [args]
This has to be merged AFTER https://github.com/apt-sim/AdePT/pull/387

Added non-consecutive reproducible track id

---

include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh

This fixes some leftovers from #393, as those parameters are unused if compiled without `ADEPT_DEBUG_TRACK`

[mini] fix unused parameters

---

Jenkinsfile
jenkins/adept-ctest.cmake
test/regression/CMakeLists.txt
test/regression/scripts/reproducibility.sh

This PR fixes the CI.
There was a problem with the CI for the split kernels:
Before, the export of the first option was overwritten by the first, such that the split kernels would be compiled without the async mode, which would already fail at CMake configuration, leading the full CI to fail.
Furthermore, there seems to be a reproducibility issue with async AdePT if there are no GPU regions, to be investigated

fix CI, disable reproducibility_regions test for async AdePT

---

include/AdePT/kernels/electrons.cuh
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h
src/AdePTTrackingManager.cc

This is an initial cleanup of the RK pusher. It introduces a couple of fixes and adds comments to the algorithm:
- Crossing a boundary in the first step now checks and detects back-scattering, in which case it returns rather than reducing the integration step.
- The last linear step was moving the track with the corrected arc fraction matching the chord intersection. This approximates better the length of the final arc step, but puts the point not on the boundary and biases the next step in the next volume
- The new direction after the RK advance was not normalized, generating errors downstream navigation
Note: there is also a printout improvement commit - if we want to keep this separate we can rebase instead of squash

Field cleanup

---

CMakeLists.txt
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/kernels/gammas_split.cuh
include/AdePT/magneticfield/fieldPropagatorConstBz.h

This PR cleans / fixes 3 things:
1. a missing include of `<optional>` which was discovered with a different compiler
2. it cleans the macros for the surface model for the safety calculation (which were actually only needed to ensure the correct vecgeom version) in the kernels, which can now be done that VecGeom is tagged and the surface model merged.
3. It fixes the CMake version check logic. Due to string comparisons, all kinds of ugly misses happened. Now, it correctly identifies and rejects older versions and accepts correct versions.

clean kernel and fix vecgeom version check

---

include/AdePT/core/Track.cuh
include/AdePT/kernels/electrons_split.cuh

In the monolithic kernel a branched RNG state is generated at the beginning before all the threads start diverging.
This was still done in the current split kernel approach and then stored inside the track. However, this is not needed, as the branched RNG state should only be generated in the interaction kernels where it is really needed.
This PR accelerates 64 ttbar events in CMS2018 with 16 threads from 160s to 145s.

remove rng state from split kernels

---

CMakeLists.txt
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h
test/unit/testField/electrons.cu

- The last exited state must be reset in the field propagator, if not done by `ComputeStepAndNextVolume` when finding the first parent not containing the point. This is needed because the track may return to the same volume due to BS or curvature.
- Added detection of a first step being zero in magnetic field, which can be used in future correlated with normal computation to signal back-scattering. Currently, the returned value is not used.
- Cleanup of pushes for readability in the field propagator.
- Tweaked some debug printouts.
Note: This PR removes the vast majority of tracks that get stuck at boundaries when used with VecGeom 2.0.0-rc5, but is also compatible with 2.0.0-rc4

Tweaks for navigation in field.

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/Track.cuh
include/AdePT/core/TrackDebug.cuh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h
scripts/trajectory.py

Added scripts/trajectory.py to visualise debugged tracks.
Compile with -DADEPT_DEBUG_TRACK=2. Debug your app and extract the track number, then rerun your app using: 
```
ADEPT_DEBUG_TRACK=79017435789256 myApplication > output.txt
```
Run the script like: 
```
python3 trajectory.py --equal-aspect --dir-fraction 0.01 --input-file track_log.txt --min-step 1 --max-step 1000
```
The options are explained in detail in the script.

Track debug visualization

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransportStruct.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/kernels/gammas_split.cuh

Separate the Relocation kernels for Electrons and gammas into a _setup kernel_ which decides whether a track will relocate, do an interaction, or continue to the next step, and a _relocation kernel_ in which the actual geometry calls are performed.
The reason for this split is that the current relocation kernels, specially in the case of electrons and positrons are very divergent. Only a small portion of the tracks in a warp will do a relocation, but the geometry calls involved are costly, which can slow down the rest of the threads in that warp.
These changes haven't shown a speedup so far in runs without a B-field, but the split should improve profiling results by isolating the relocation code.

Split relocation kernels

---

include/AdePT/core/AdePTTransport.cuh
include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/integration/AdePTTrackingManager.hh
src/AdePTTrackingManager.cc

This fixes an issue in Sync AdePT that probably stems from #386 but could be even older:
In Sync AdePT, one thread initializes the common data on the GPU, however, all threads would try to delete them in the destructor, causing double frees and crashes.
This is fixed by flagging which thread did the common init and only that thread deallocates the common data in the destructor.

only thread that allocated may deallocate common data in Sync AdePT

---

include/AdePT/core/AsyncAdePTTransport.cuh

This PR fixes the crash that happens if AdePT runs out of hit slots for async AdePT in almost all cases.
It is checked whether there are more particles in flight than there are hit slots left (as the number is only an estimate, I added a factor of 1.5). If that is the case, the next step might cause a crash. Then, one has to wait for the DeviceBuffers to be ready to swapped, before one can continue with the swap (which frees the hit slots), before the next step can be taken.
Note that if more tracks are in flight than total hit slots are available, any time all tracks could generate a hit and cause a crash and overflow. This is not fixable by waiting for freeing the hit slots, this requires simply more slots or less threads (which leads to more slots per thread and less particles in …

Fix HitSlot overflow

---

include/AdePT/core/AsyncAdePTTransport.cuh

Reducing the block size from the previous 256 to 32 provides a speedup in Bfield runs, while not affecting runs without a field. This has been tested on two different GPUs:
```
Nvidia RTX 4080
CMS 2018, 8 Threads x 32 TTbar events
```
**No field**
| Kernels    | Time 256 | Time 32 |
|------------|----------|---------|
| Monolithic | 177      | 175     |
| Split      | 182      | 181     |
**3.8 T Field**
| Kernels    | Time 256 | Time 32 | Speedup |
|------------|----------|---------|---------|
| Monolithic | 339      | 292     | 1.16    |
| Split      | 348      | 296     | 1.17    |
```
Nvidia RTX 4090
CMS 2018, 16 Threads x 128 TTbar events
```
**3.8 T Field**
| Kernels    | Time 256 | Time 32 | Speedup |
|------------|----------|---------|---------|
| Monolithic | 856      | 600     | …

Reduce block size for transport kernels

---

examples/Example1/src/RunAction.cc
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h

The field propagator was limiting arc integration by the bending error only, validating the advance against the current safety. This actually uses the current safety to limit the integration step to a possibly larger value.
We have to measure better, but I see a runtime gain of ~20% in CMS using this

Integrate in safety steps

---

src/AdePTGeant4Integration.cpp

Previously, we set the touchable handle of the postStepPoint. However, in Athena, the `track->GetNextVolume` method is used, which requires the NextTouchableHandle of the track to be set. This is set to the touchable handle of the postStepPoint.

add nextTouchableHandle to track MC truth information

---

CMakeLists.txt
examples/common/include/MagneticFields.hh

This fixes a crash that was observed running the example1 with an external B field map:
While the B field on the GPU in texture memory is always clamped and therefore secure against out-of-bounds access, the B field on the CPU that we use in our examples is not. This requires initializing the B field type as clamped.
As the B field type of the reader and writer must be the same in covfie, (and we require an unclamped version for the texture memory), the clamped B field is generated separately from the unclamped one, which is read from file.
The covfie version is updated.

Fix CPU B field in examples, update covfie version

---

CMakeLists.txt
README.md
examples/Example1/example1.cpp
examples/Example1/src/DetectorConstruction.cc
include/AdePT/copcore/Macros.h
include/AdePT/copcore/ranluxpp/mulmod.h
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/core/ScoringCommons.hh
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/integration/AdePTTrackingManager.hh
include/AdePT/magneticfield/RkIntegrationDriver.h
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc
test/regression/IntegrationTest/integrationTest.cpp
test/regression/IntegrationTest/src/DetectorConstruction.cc
test/unit/compare_integration_precision.cpp
test/unit/test_magfieldRK.cpp

This PR adds stricter compiler flags to AdePT. Additionally, a new compile time option is introduced to enforce some of the flags. This setting enforces the same error flags as CMSSW. If they are not enforced, still, they are printed as warnings.
This new setting revealed many minor issues, but also a bigger one, where the `parentTrackInfo` was used instead of the `hostTrackInfo`.
Note that even stricter flags could be set, but those reveal countless issues in VecGeom and G4VG, so it is left for future cleaning.

Add stricter compiler flags

---

include/AdePT/core/AdePTConfiguration.hh
src/AdePTTrackingManager.cc

G4 applications don't necessary need to use a G4RunManager. In that case, AdePT can retrieve the number of threads via the AdePTConfig, which is passed to the constructor of the AdePTTrackingManager. Then, in the physicslist, the number of threads must be passed via the AdePTConfig to the AdePTTrackingManager. Needed in CMSSW.
This PR adds a safe guard for the possible nullptr access for the G4RunManager, sets a default value for fNumThreads and deletes an used variable.

Enable using fNumThreads from AdePTconfig

---

include/AdePT/integration/HostTrackDataMapper.hh

This fixes a warning of a potentially uninitialized member of the hosttrackdata. Now it is initialized to the G4 default value of 0.

[mini] fix uninitialized warning

---

include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh

This PR refactors the monolithic kernels to enable a central spot for implementing a custom stepping actions for experiments.
As the experiment's frameworks have their own custom stepping actions where they decide to kill unwanted tracks, it would be beneficial if AdePT supports implementing such a stepping action in a straightforward way.
Currently, the `survive()` function was called in multiple places in the monolithic kernels. Therefore, this PR suggests to refactor the kernels such that only a surviveFlag is set to true if a track survives such that before the actual `survive` call at the end of the kernel, a stepping action could be added.
Note that this change originally did affect the run time as it forced some synchronization under the hood. After adding a few `__syncwarp()` …

Refactoring the monolithic kernels for potential stepping action

---

include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/integration/AdePTGeant4Integration.hh
include/AdePT/integration/HostTrackDataMapper.hh
src/AdePTGeant4Integration.cpp
src/AdePTTrackingManager.cc

This PR fixes a bug in the access of the HostTrackData, so only a local copy was modified and not the stored data.
This led to many tracks using the default constructed HostTrackData. The fix does not change the run time. This was found during the LHCb validation, as the joining of hits with their parents did not work:
Now it does:

Fix access to HostTrackData

---

include/AdePT/core/Track.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/kernels/gammas_split.cuh

When using split kernels, we keep a pool of HepEm tracks that we use to avoid instantiating and initializing a track in each kernel of a step. We can take advantage of this by re-using and not re-initializing tracks after the first step for a particle. 
Acessing and setting HepEm track data is a large source of long scoreboard stalls. This change provides a speedup of around 8% for the split kernels. The same optimization has also been tried on the monolithic kernels but it doesn't seem to give any speedup in that case. 
There is a small diference in energy deposition, which is likely caused by the fact that fields like the numIALeft or mscData are stored in `double` by G4HepEm and `float` by AdePT. By keeping these fields in the HepEm track and avoiding these two conversions the results …

Reuse already initialized HepEm tracks in split kernels mode

---

include/AdePT/kernels/electrons_split.cuh

An overlooked `vecgeom::Precision` prevented compilation of the split kernels in mixed-precision mode in some machines.

Replace overlooked vecgeom::Precision with rk_integration

---

src/AdePTGeant4Integration.cpp

Previously, only the postStepPoint touchable was set. This PR alsp sets the preStepPoint touchable. Needed for CMS, as otherwise this line from a sensitive detector 
```c++
const G4String& rname = aStep->GetTrack()->GetVolume()->GetLogicalVolume()->GetRegion()->GetName();
``` 
crashes.

[mini] Set current touchable from prestep point

---

include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/core/Track.cuh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/kernels/gammas_split.cuh
src/AdePTGeant4Integration.cpp

Previously only the `Track->globalTime` and the `postStepPoint->globalTime` was set. This PR also returns and sets the `preStepPoint->globalTime` as required by Athena, CMSSW, and Gauss.

return preStep global time

---

include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/electrons_split.cuh

Reported by @dkonst13 :
The proper time was not calculated correctly in AdePT:
It should be  $t_{proper} += \Delta_t * m_e / E_{tot}$ with $E_{tot} = m_e + E_{kin}$.
See also in G4 [here](https://gitlab.cern.ch/geant4/geant4/-/blob/master/source/processes/transportation/src/G4Transportation.cc?ref_type=heads#L553)

[mini] Fix proper time

---

include/AdePT/core/AdePTTransport.h
include/AdePT/core/AdePTTransport.icc
include/AdePT/core/AdePTTransportInterface.hh
include/AdePT/core/AsyncAdePTTransport.hh
include/AdePT/core/AsyncAdePTTransport.icc
include/AdePT/integration/AdePTGeant4Integration.hh
src/AdePTTrackingManager.cc

Due to the nuclear processes, we need each integration layer object to hold a reference to the thread's HepEmTrackingManager. This was achieved by initializing each integration object per thread after the AdePT common initialization. However, the code gave the impression that this was happening in the AsyncAdePTTransport constructor, while in reality this is called only once per run, by the first thread that runs the initialization.
With these changes, the unneeded code is removed from the constructor, and the integration objects are default constructed, rather than being created at AdePT initialization. Each thread stores its HepEmTrackingManager on the corresponding integration object with a call after retrieving the pointer to the common AsyncAdePTTransport.

Async AdePT initialization cleanup

---

include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/AsyncAdePTTransportStruct.cuh
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/core/Track.cuh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/electrons_async.cuh
include/AdePT/kernels/electrons_split.cuh
include/AdePT/kernels/gammas.cuh
include/AdePT/kernels/gammas_async.cuh
include/AdePT/kernels/gammas_split.cuh
include/AdePT/magneticfield/CompareResponses.h
include/AdePT/magneticfield/ConstBzFieldStepper.h
include/AdePT/magneticfield/ConstFieldHelixStepper.h
include/AdePT/magneticfield/fieldPropagatorConstBany.h
include/AdePT/magneticfield/fieldPropagatorConstBz.h
include/AdePT/magneticfield/fieldPropagatorRungeKutta.h
include/AdePT/navigation/SurfNavigator.h
test/unit/testField/electrons.cu
test/unit/testField/gammas.cu
test/unit/testField/testField.cu
test/unit/testField/testField.cuh
test/unit/test_Bfield_step_debugger.cpp

Drop the usage of VECGEOM_FLOAT_PRECISION (Precision=float) and replace Precision<->double.
This prepares for the `v2` release of VecGeom where `Precision` lives only in `vecgeom` namespace and will break the compilation of AdePT. The change of Precision->double will preserve the capability to run also with older VecGeom. VECGEOM_FLOAT_PRECISION was an experimental feature known to have big limitations for realistic setups anyway.

Changing vecgeom::Precision to double
