apt-sim/AdePT

CMakeLists.txt
README.md
cmake/RecordCmdLine.cmake

This adds VecCore and VecGeom as dependencies for the project. It adds also automatic recording and generation of a script to replay the last build command. The README file was updated.

Added cmake dependencies.

---

.github/workflows/clang-format.yml
test/example_add.cu

Latest version of action also includes CUDA source files

Update clang-format action version

---

base/inc/AdePT/BlockData.h

Fix for counting used elements in BlockData.

---

CMakeLists.txt
examples/CMakeLists.txt
examples/Raytracer_Benchmark/ArgParser.h
examples/Raytracer_Benchmark/CMakeLists.txt
examples/Raytracer_Benchmark/Color.h
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp
examples/Raytracer_Benchmark/RaytraceBenchmark.cu
examples/Raytracer_Benchmark/Raytracer.cpp
examples/Raytracer_Benchmark/Raytracer.h

I have imported files: Raytracer.h, Color.h, ArgParser.h, Raytracer.cpp, RaytraceBenchmark.cu and RaytraceBenchmark.cpp from VecGeom, branch raytracer_prot. 
The executable made is "RaytraceBenchmark". 
The simple way to run it is `./RaytraceBenchmark -gdml_name <path_to_gdml_file> <other_options>`, where <other_options> are defined in RaytraceBenchmark.cpp.

Import RaytraceBenchmark from VecGeom/raytracer_prot

---

base/inc/CopCore/include/CopCore/PhysicalConstants.h
base/inc/CopCore/include/CopCore/SystemOfUnits.h

No need to reinvent the wheel for units and physics constants.

[copcore] Porting physics constants and system of units from GeantV.

---

examples/FisherPrice_Alpaka/particle.h

The particle.h file form the FisherPrice_Alpaka directory was missing.
This MR add that.

Add missing particle class.

---

examples/Raytracer_Benchmark/RaytraceBenchmark.cu

A bit more cleanup in the ray tracer example

Removal of extra dead code and using COPCORE_CUDA_CHECK for RT example.

---

examples/Raytracer_Benchmark/RaytraceBenchmark.hpp

Fixed warning about namespace not being inline in RaytraceBenchmark.

---

examples/Example1/CMakeLists.txt
examples/Example1/example1.cu
examples/Example2/CMakeLists.txt
examples/Example2/example2.cu
physics/processes/inc/pair_production.h
tracking/inc/track.h

I didn't touch `examples/FisherPrice_cu/`, not sure if it makes sense to convert.

Convert examples to RANLUX++

---

base/inc/AdePT/SparseVector.h
base/inc/CopCore/include/CopCore/Global.h
test/CMakeLists.txt
test/test_sparsevector.cu
test/test_sparsevector_cpu.cpp

SparseVector is a variable-size vector, adopting pre-allocated space and targeting both host/device use. It supports in-place construction while distributing concurrently elements. The vector allows releasing elements and checking if a given index is in use. It provides getters for the number of shared, used, and total elements, as well as ratios representing sparsity, shared, and selected fractions. It supports selection operations using arbitrary predicate functions and executes concurrently as a kernel. SparseVector can be compacted concurrently into another SparseVector.
Commented tests demonstrating main functionality: test_sparsevector (GPU) and test_sparsevector_cpu (CPU).

Implementation of a sparse vector.

---

Jenkinsfile
jenkins/adept-ctest.cmake

Improvements:
- Add PreCheckNode stage
-

Github <---> Jenkins improvements

---

examples/Raytracer_Benchmark/Color.h
examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
examples/Raytracer_Benchmark/Raytracer.cpp

This fixes some issues preventing using single-volume setups + other minor fixes.

Fixes in ray-tracing example: color treatment, setups with a single volume

---

examples/Example4/createTracks.h
examples/Example4/example4.cu
magneticfield/inc/ConstBzFieldStepper.h
magneticfield/inc/ConstFieldHelixStepper.h
magneticfield/inc/fieldPropagatorConstBz.h
physics/processes/inc/energy_loss.h
physics/processes/inc/pair_production.h
physics/processes/inc/process.h
physics/processes/inc/process_list.h
physics/processes/inc/transportation.h
tracking/inc/printTracks.h
tracking/inc/track.h

This does several unit-related fixes in example4, transportation+magnetic field, processes, and track. It fixes also some bugs in the field propagator.

Fixes example4

---

CMakeLists.txt
base/inc/CopCore/include/CopCore/PhysicalConstants.h
base/inc/CopCore/include/CopCore/SystemOfUnits.h
examples/Example2/example2.cpp
examples/Example4/example4.cpp
examples/Raytracer_Benchmark/RaytraceBenchmark.cpp

Adapted to changes done in 17.07.20 in CLHEP

Adapted the system of units to Geant4, using PDG 2019 values.

---

examples/Example6/example6.cu

Now that AdePT and G4HepEm agree on the units, we don't need to transform the values on-the-fly.

example6: Remove unit conversions

---

examples/Example6/example6.cu
examples/Example8/example8.cu

Even if depositing the gamma's energy, the primary gets slightly deflected.

Apply primary's direction change in Bremsstrahlung

---

CMakeLists.txt
examples/Example1/CMakeLists.txt
examples/Example2/CMakeLists.txt
examples/Example4/CMakeLists.txt
examples/Example5/CMakeLists.txt
examples/Example6/CMakeLists.txt
examples/Example8/CMakeLists.txt
examples/Example9/CMakeLists.txt
examples/TestEm3/CMakeLists.txt

Move download of GDML into top-level `CMakeLists.txt`

Add all examples as tests

---

examples/CMakeLists.txt
examples/ECS/CMakeLists.txt
examples/ECS/CudaHelpers.h
examples/ECS/Kernels.h
examples/ECS/README.md
examples/ECS/ecs.cu
examples/ECS/ecs.h
examples/ECS/mergeAndSortBlocks.cuh

An Entity Component System is what game engines use to achieve an SoA data layout.
Here, SoA-style data is compared with AoS-style data, and both are processed with
indentical kernels using structs of references.
This is the code that was used to create the results discussed in
https://indico.cern.ch/event/1020971/
See #72.

Add ECS example.

---

test/test_sparsevector.cu

Added missing synchronization. Closes #109

Fix sync in test_sparsevector

---

examples/Example9/electrons.cu
examples/Example9/gammas.cu
examples/TestEm3/electrons.cu
examples/TestEm3/gammas.cu

This slightly reduces the number of particles in flight, but no change to performance.

Filter particles earlier that left the world

---

magneticfield/inc/fieldPropagatorConstBz.h

If propagation in magnetic field doesn't make any progress, start reducing the `safeMove` to try smaller chord steps. Geant4 only does it after a number of zero-steps, but this would require a counter per track that we generally want to avoid.
Fixes #145

Reduce safeMove in case of no progress

---

magneticfield/inc/fieldPropagatorConstBz.h

Fix for field safe move estimation.

---

examples/Example10/example10.cpp
examples/Example11/example11.cpp
examples/Example12/example12.cpp
examples/Example13/electrons.cu
examples/Example13/example13.cpp
examples/Example13/example13.cu
examples/Example13/example13.cuh
examples/Example14/AdeptIntegration.cu
examples/Example14/Track.cuh
examples/Example14/electrons.cuh
examples/Example14/src/DetectorConstruction.cc
examples/Example14/src/PhysListHepEm.cc
examples/Example5/example5.cpp
examples/Example5/example5.cu
examples/Example6/example6.cpp
examples/Example7/geant4_mock.cc
examples/Example8/example8.cpp
examples/Example9/example9.cpp
examples/TestEm3/TestEm3.cpp
examples/TestEm3/TestEm3.cu
examples/TestEm3/TestEm3.cuh
examples/TestEm3/electrons.cu
examples/TestEm3MT/TestEm3.cpp
examples/TestEm3MT/TestEm3.cu
examples/TestEm3MT/TestEm3.cuh
examples/TestEm3MT/electrons.cu

This requires setting the world for tracking in `G4TransportationManager` and storing two additional values in the `Track` structure.

Update G4HepEm and switch to Urban MSC model

---

examples/FisherPrice_Alpaka/CMakeLists.txt
examples/FisherPrice_Alpaka/alpaka_fisher_price.cu
examples/FisherPrice_Alpaka/particleProcessor.h
examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu

The alpaka API has changed some time ago. This PR makes AdePT's alpaka examples compile again.

Update alpaka API usage

---

examples/Example14/include/HepMC3G4Interface.hh
examples/Example14/src/HepMC3G4AsciiReader.cc
examples/Example14/src/HepMC3G4Interface.cc

fixing https://github.com/apt-sim/AdePT/issues/210 
(removing unnecessary delete)

removing unnecessary delete

---

examples/Example19/example.cuh

Here's the missing commit.
Fix #220.

[ex19] Fix a wrong index.

---

examples/Example19/README.md
examples/Example19/example.h
examples/Example19/main.cpp
examples/Example19/main.cu

For TestEm3, the gun needs to be placed at negative x. When "estEm3" is encountered in the gdml name, the gun will shift itself.
@bernhardmgruber 
```
Run time: 0.153657
Mean energy deposit          9.87835 GeV <--
Mean number of gamma         5199.97
```
:+1:

[ex19] Allow for placing the particle gun from the host.

---

CMakeLists.txt
base/inc/AdePT/BenchmarkManager.h
benchmark/plot_error_bars.py
benchmark/run_bechmark.sh
examples/Example13/example13.cpp
examples/Example17/CMakeLists.txt
examples/Example17/include/DetectorConstruction.hh
examples/Example17/include/Run.hh
examples/Example17/include/RunAction.hh
examples/Example17/include/SteppingAction.hh
examples/Example17/include/TrackingAction.hh
examples/Example17/src/ActionInitialisation.cc
examples/Example17/src/EventAction.cc
examples/Example17/src/Run.cc
examples/Example17/src/RunAction.cc
examples/Example17/src/SteppingAction.cc
examples/Example17/src/TrackingAction.cc

* BenchmarkManager class
* Example13 benchmark
* Example17 benchmark

Benchmarking scripts

---

examples/Example14/src/PrimaryGeneratorAction.cc
examples/Example17/src/PrimaryGeneratorAction.cc

This gives the proper `G4WT` prefixes.

Use G4endl with G4cout

---

examples/Example3/CMakeLists.txt

CI is currently broken due to this

[Example3] disabled IPO due to CMake change of policy.

---

Jenkinsfile

To implement this request: https://its.cern.ch/jira/browse/SPI-2499

Jenkinsfile: allow gcc11

---

README.md

This branch is intended as playground for R&D investigations not bound to the library-based pipeline.

Initial commit for the AdePT legacy branch.

---

examples/common/include/ParticleGun.hh
examples/common/src/ParticleGun.cc
include/AdePT/copcore/Allocator.h
include/AdePT/copcore/VariableSizeObjAllocator.h
include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/HostScoringStruct.cuh
include/AdePT/core/TrackData.h
src/AdePTGeant4Integration.cpp

When introducing the transport interface, I came a cross a few things such as compiler warnings, clang-format issues, memory optimisations and better debugging which are independent of the transport interface.
I factored out these changes into this PR.

A few fixes and optimisations

---

src/AdePTTrackingManager.cc

In case there are no GPU regions defined, we return tracks to Geant4. This MR moves the check for an empty list of GPU regions to the `HandoverOneTrack` method, to avoid an issue where we would call the `PreUserTrackingAction` twice for tracks that were returned to Geant4.

Earlier no GPU region check

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/AsyncAdePTTransport.icc

This just enables the surface model replacing the solid one when ADEPT_USE_SURF is ON

Enabled surface model for the async mode.

---

include/AdePT/core/AdePTConfiguration.hh
include/AdePT/integration/AdePTConfigurationMessenger.hh
include/AdePT/integration/AdePTTrackingManager.hh
include/AdePT/kernels/electrons.cuh
src/AdePTConfigurationMessenger.cc
src/AdePTTrackingManager.cc

This adds an input option to kill all electrons, positrons, and gammas immediately, which is a useful measure for optimal performance.

[mini] Add speedoflight option

---

include/AdePT/core/AdePTScoringTemplate.cuh
include/AdePT/core/HostScoringImpl.cuh
include/AdePT/core/PerEventScoringImpl.cuh
include/AdePT/core/ScoringCommons.hh
include/AdePT/kernels/electrons.cuh
include/AdePT/kernels/gammas.cuh
src/AdePTGeant4Integration.cpp

Add track weight to GPUHits and set it to the reconstructed track used for scoring

Pass track weight to scoring

---

CMakeLists.txt
include/AdePT/core/PerEventScoringImpl.cuh

This reverts #370. The flag is in fact used in G4HepEm and important.

Fix cleaning

---

include/AdePT/core/AsyncAdePTTransport.cuh

This adresses the long-standing particle injection bug where some particles may be injected after their events are finished.
This bug only appears in specific runs, such as running the `testEm3` geometry with large events and a large number of leaks or oversubscribing the CPU threads. This PR solves it by synchronizing the particle injection stream at the end of every iteration.
While this fix solves the issue, it is not adressing the root  cause of the bug (As the logic doesn't require a synchronization), and should be removed once the underlying bug is understood and fixed.
This temporary fix doesn't cause any measurable slowdown in runs using the `CMS2018` geometry with ttbar events.

Temporary injection bug fix

---

include/AdePT/core/AsyncAdePTTransport.cuh
include/AdePT/core/PerEventScoringImpl.cuh

This PR fixes two issues, where the first one caused the CI to fail frequently.
1. There was a race condition in `SwapDeviceBuffers` and `TransferHitsToHost`:
The Transport Thread would call `SwapDeviceBuffers` and set the DeviceState to `NeedTransferToHost` immediately, although the copy of the numbers of GPU steps was copied asynchronously. Then, the Step processing thread in `TransferHitToHost` would check for the device state to be in the state `NeedTransferToHost` to start the transfer. However, in rare occasions, the copy of the number of GPU steps to be copied was not yet complete, leading to the wrong number of steps being copied, which then subsequently led to threads processing the steps of a different thread, which would throw an error and break reproducibility. This is fixed …

fix synchronization issue between SwapDeviceBuffers and TransferHitsToHost

---

scripts/trajectory.py

Now it shows unscaled energy in the viridis map. It also shows the real step range found and not the one provided as input.

[mini] Improved track visualization script 
